// COPYRIGHT Dassault Systemes 2012
//===================================================================
//
// BITCreateAssemSndDlg.h
// The dialog : BITCreateAssemSndDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  Jul 2012  Creation: Code generated by the CAA wizard  ali
//===================================================================
#ifndef BITCreateAssemSndDlg_H
#define BITCreateAssemSndDlg_H

#include "CATDlgDialog.h"
#include "CATDlgInclude.h"

//----------------------------------------------------------------------

/**
 * Describe the purpose of your panel here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog framework.
 * (consult base class description).
 */
class BITCreateAssemSndDlg: public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( BITCreateAssemSndDlg, CATDlgDialog )

  public:

  BITCreateAssemSndDlg();


  virtual ~BITCreateAssemSndDlg();

  void Build ();


  protected:
  /**
  * Callback on PushBActivate of _PushButtonJH
  *
  * <br><b>Role</b>: This method handles the PushBActivate event and does
  *   a check on ...
  *
  * @param Command [in]
  *   Pointer to the publisher of the event.
  * @param Notification [in]
  *   Pointer to the notification representing the event.
  * @param data [in]
  *   Possible useful data transmitted to the command OnPushButtonJHPushBActivateNotification
  *
  *
  */
  virtual void OnPushButtonJHPushBActivateNotification (CATCommand *, CATNotification* , CATCommandClientData data);
  /**
  * Callback on ComboSelect of _ComboXS
  *
  * <br><b>Role</b>: This method handles the ComboSelect event and does
  *   a check on ...
  *
  * @param Command [in]
  *   Pointer to the publisher of the event.
  * @param Notification [in]
  *   Pointer to the notification representing the event.
  * @param data [in]
  *   Possible useful data transmitted to the command OnComboXSComboSelectNotification
  *
  *
  */
  virtual void OnComboXSComboSelectNotification (CATCommand *, CATNotification* , CATCommandClientData data);
  /**
  * Callback on PushBActivate of _PushButtonL03
  *
  * <br><b>Role</b>: This method handles the PushBActivate event and does
  *   a check on ...
  *
  * @param Command [in]
  *   Pointer to the publisher of the event.
  * @param Notification [in]
  *   Pointer to the notification representing the event.
  * @param data [in]
  *   Possible useful data transmitted to the command OnPushButtonL03PushBActivateNotification
  *
  *
  */
  virtual void OnPushButtonL03PushBActivateNotification (CATCommand *, CATNotification* , CATCommandClientData data);
 

  /**
  * Callback on PushBActivate of _PushButtonL02
  *
  * <br><b>Role</b>: This method handles the PushBActivate event and does
  *   a check on ...
  *
  * @param Command [in]
  *   Pointer to the publisher of the event.
  * @param Notification [in]
  *   Pointer to the notification representing the event.
  * @param data [in]
  *   Possible useful data transmitted to the command OnPushButtonL02PushBActivateNotification
  *
  *
  */
  virtual void OnPushButtonL02PushBActivateNotification (CATCommand *, CATNotification* , CATCommandClientData data);
  /**
  * Callback on PushBActivate of _PushButtonL01
  *
  * <br><b>Role</b>: This method handles the PushBActivate event and does
  *   a check on ...
  *
  * @param Command [in]
  *   Pointer to the publisher of the event.
  * @param Notification [in]
  *   Pointer to the notification representing the event.
  * @param data [in]
  *   Possible useful data transmitted to the command OnPushButtonL01PushBActivateNotification
  *
  *
  */
  virtual void OnPushButtonL01PushBActivateNotification (CATCommand *, CATNotification* , CATCommandClientData data);
  /**
  * Callback on WindClose of _BITCreateAssemSndDlg
  *
  * <br><b>Role</b>: This method handles the WindClose event and does
  *   a check on ...
  *
  * @param Command [in]
  *   Pointer to the publisher of the event.
  * @param Notification [in]
  *   Pointer to the notification representing the event.
  * @param data [in]
  *   Possible useful data transmitted to the command OnBITCreateAssemSndDlgWindCloseNotification
  *
  *
  */
  virtual void OnBITCreateAssemSndDlgWindCloseNotification (CATCommand *, CATNotification* , CATCommandClientData data);

  private:


//CAA2 WIZARD WIDGET DECLARATION SECTION
 CATDlgFrame*      _Frame037;
 CATDlgLabel*      _Label039;
 CATDlgEditor*      _EditorL01;
 CATDlgLabel*      _Label041;
 CATDlgLabel*      _Label042;
 CATDlgEditor*      _EditorL02;
 CATDlgLabel*      _Label044;
 CATDlgLabel*      _Label045;
 CATDlgEditor*      _EditorL03;
 CATDlgLabel*      _Label047;
 CATDlgPushButton*      _PushButtonL02;
 CATDlgLabel*      _Label051;
 CATDlgEditor*      _EditorL05;
 CATDlgLabel*      _Label054;
 CATDlgLabel*      _Label067;
 CATDlgEditor*      _EditorL04;
 CATDlgLabel*      _Label069;
 CATDlgPushButton*      _PushButtonL01;
 CATDlgLabel*      _Label092;
 CATDlgEditor*      _EditorCD;
 CATDlgLabel*      _Label094;
 CATDlgFrame*      _Frame098;
 CATDlgLabel*      _Label099;
 CATDlgFrame*      _Frame055;
 CATDlgLabel*      _Label058;
 CATDlgFrame*      _Frame072;
 CATDlgLabel*      _Label064;
 CATDlgEditor*      _EditorFB;
 CATDlgLabel*      _Label066;
 CATDlgLabel*      _Label073;
 CATDlgEditor*      _EditorJZ;
 CATDlgLabel*      _Label075;
 CATDlgPushButton*      _PushButtonL03;
 CATDlgLabel*      _Label078;
 CATDlgEditor*      _EditorZA;
 CATDlgLabel*      _Label080;
 CATDlgLabel*      _Label081;
 CATDlgEditor*      _EditorZB;
 CATDlgLabel*      _Label083;
 CATDlgLabel*      _Label084;
 CATDlgEditor*      _EditorND;
 CATDlgLabel*      _Label086;
 CATDlgLabel*      _LabelWZ;
 CATDlgEditor*      _EditorWZ;
 CATDlgLabel*      _Label091;
 CATDlgCombo*      _ComboXS;
 CATDlgFrame*      _Frame095;
 CATDlgLabel*      _Label096;
 CATDlgFrame*      _Frame100;
 CATDlgLabel*      _Label101;
 CATDlgRadioButton*      _RadioButton102;
 CATDlgRadioButton*      _RadioButton103;
 CATDlgLabel*      _Label104;
 CATDlgEditor*      _Editor105;
 CATDlgLabel*      _Label106;
 CATDlgEditor*      _Editor107;
 CATDlgLabel*      _Label108;
 CATDlgLabel*      _Label109;
 CATDlgEditor*      _Editor110;
 CATDlgEditor*      _Editor111;
 CATDlgPushButton*      _PushButtonJH;
 CATDlgLabel*      _Label113;
 CATDlgLabel*      _Label114;
 CATDlgLabel*      _Label115;
 CATDlgLabel*      _Label117;
 //END CAA2 WIZARD WIDGET DECLARATION SECTION
public:
	void ActOnOK(CATCommand * cmd, CATNotification* evt , CATCommandClientData data);
   void OnMultiListInformationListSelectNotification (CATCommand *, CATNotification* , CATCommandClientData data);

 CATDlgNotify   * _OpenNotify;				//对话框CATDlgNotify的声明

};

//----------------------------------------------------------------------

#endif
