// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// FirstDlg.h
// The dialog : FirstDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  Jan 2015  Creation: Code generated by the CAA wizard  ALI
//===================================================================
#ifndef FirstDlg_H
#define FirstDlg_H

#include "CATDlgDialog.h"
#include "CATDlgInclude.h"
#include "CATDlgNotify.h"

//----------------------------------------------------------------------

/**
 * Describe the purpose of your panel here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog framework.
 * (consult base class description).
 */
class FirstDlg: public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( FirstDlg, CATDlgDialog )

  public:

  FirstDlg();
  virtual ~FirstDlg();

  void Build ();


  protected:
  /**
  * Callback on PushBActivate of _PushButton021
  *
  * <br><b>Role</b>: This method handles the PushBActivate event and does
  *   a check on ...
  *
  * @param Command [in]
  *   Pointer to the publisher of the event.
  * @param Notification [in]
  *   Pointer to the notification representing the event.
  * @param data [in]
  *   Possible useful data transmitted to the command OnPushButton021PushBActivateNotification
  *
  *
  */
  virtual void OnPushButton021PushBActivateNotification (CATCommand *, CATNotification* , CATCommandClientData data);
  
  /**
  * Callback on PushBActivate of _PushButtonFM1
  *
  * <br><b>Role</b>: This method handles the PushBActivate event and does
  *   a check on ...
  *
  * @param Command [in]
  *   Pointer to the publisher of the event.
  * @param Notification [in]
  *   Pointer to the notification representing the event.
  * @param data [in]
  *   Possible useful data transmitted to the command OnPushButtonFM1PushBActivateNotification
  *
  *
  */
  virtual void OnPushButtonFM1PushBActivateNotification (CATCommand *, CATNotification* , CATCommandClientData data);
  /**
  * Callback on WindClose of _FirstDlg
  *
  * <br><b>Role</b>: This method handles the WindClose event and does
  *   a check on ...
  *
  * @param Command [in]
  *   Pointer to the publisher of the event.
  * @param Notification [in]
  *   Pointer to the notification representing the event.
  * @param data [in]
  *   Possible useful data transmitted to the command OnFirstDlgWindCloseNotification
  *
  *
  */
  virtual void OnFirstDlgWindCloseNotification (CATCommand *, CATNotification* , CATCommandClientData data);

  /**
  * Callback on PushBActivate of _PushButtonFM2
  *
  * <br><b>Role</b>: This method handles the PushBActivate event and does
  *   a check on ...
  *
  * @param Command [in]
  *   Pointer to the publisher of the event.
  * @param Notification [in]
  *   Pointer to the notification representing the event.
  * @param data [in]
  *   Possible useful data transmitted to the command OnPushButtonFM2PushBActivateNotification
  *
  *
  */
  virtual void OnPushButtonFM2PushBActivateNotification (CATCommand *, CATNotification* , CATCommandClientData data);



  
  private:


//CAA2 WIZARD WIDGET DECLARATION SECTION
 CATDlgFrame*      _FrameFM1;
 CATDlgLabel*      _LabelFM1;
 CATDlgEditor*      _EditorFM1;
 CATDlgFrame*      _FrameFM2;
 CATDlgLabel*      _LabelFM2;
 CATDlgEditor*      _EditorFM2;
 CATDlgLabel*      _LabelFM3;
 CATDlgEditor*      _Editor016;
 CATDlgLabel*      _LabelFM4;
 CATDlgLabel*      _LabelFM5;
 CATDlgFrame*      _FrameFM3;
 CATDlgPushButton*      _PushButtonFM1;
 CATDlgLabel*      _LabelFM6;
 CATDlgEditor*      _EditorFM4;
 CATDlgMultiList*      _MultiListFM1;
 CATDlgFrame*      _Frame020;
 CATDlgPushButton*      _PushButtonFM2;
 CATDlgPushButton*      _PushButton021;
//END CAA2 WIZARD WIDGET DECLARATION SECTION

 public:
 void ActOnOK(CATCommand*cmd,CATNotification*evt,CATCommandClientData data);
 void ActOnOK2(CATCommand*cmd,CATNotification*evt,CATCommandClientData data);
 CATDlgFile * pDlgFile;
 CATDlgFile * pDlgFile2;
 CATDlgNotify * _AddNotify;

};

//----------------------------------------------------------------------

#endif
