# COPYRIGHT Dassault Systemes 2015
#======================================================================
# Imakefile for module TrainModule.m
#======================================================================
#
#  Jan 2015  Creation: Code generated by the CAA wizard  ALI
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES =   DI0PANV2 CATMathematics CATDialogEngine \
					CATSchItfCPP CATDraftingInterfaces CATTPSItf \			
					   JS0GROUP JS0FM CATPspUtilities \
					   CATApplicationFrame  CATViz \
					   CATMecModInterfaces CATObjectSpecsModeler \
					   CATGeometricObjects CATMathStream CATTopologicalObjects \
					   CATGeometricOperators CATObjectModelerBase KnowledgeItf \
					   CATGitInterfaces CATSketcherInterfaces CATVisualization \
					   CATMeasureGeometryInterfaces CATInteractiveInterfaces \
					   CATProductStructure1 CATProcessInterfaces CATPartInterfaces \
					   CATTopologicalOperators CATManufacturingInterfaces CATMechanicalModeler \
					   JS0FM JS0GROUP CATXMLParserItf \
					   AD0XXBAS CD0FRAME \
					DI0STATE AC0SPBAS \
					ProcessInterfaces \
					CATManufacturingInterfaces \
					CATSurfaceMachiningInterfaces \
					CATProductStructure1 \
					 CATLiteralFeatures KnowledgeItf \		
				    CATIAApplicationFrame \
					CATProductStructure1 \
					KnowledgeItf \
					CATPartInterfaces  CATSketcherInterfaces \
					CATMechanicalModeler \
					CATGitInterfaces  \
					CATVisualization \
					CATAssemblyInterfaces \
					CATConstraintModeler \
					CATMathStream \
					CATConstraintModelerItf \
					CATUdfInterfaces  \
					JS0SCBAK  \
					CATTopologicalOperators \
					CATInteractiveInterfaces \
					Mathematics  \
					 CATPrismaticMachiningInterfaces CATPartInterfaces \
					PrismaticMachiningInterfacesUUID \
					CATSketcherInterfaces CATUdfInterfaces \
					CATSaiSpaceAnalysisItf \
					   CATMechanicalCommands       \
					   CATVisualization    \
					  CATCclInterfaces            \
					  CATInteractiveInterfaces \
						 CATMeasureGeometryInterfaces    AC0XXLNK \
						SpecsModeler\
						CK0FEAT JS0CORBA \
						YP00IMPL YN000MAT\
						CATCGMGeoMath \
							 CATWkAssyInterface CATAssemblyInterfacesUUID \
						CATMechanicalModelerUI \
						CATTopologicalObjects   \
						CATConstraintModeler \
						CATGeometricOperators \
						InfItf   \
						InfItfCPP  \
						CATTTRSItf \
						CATTTRSUUID \
						InfProIDL \
						GeoNurbsTools \
						CATFreeFormOperators \
						CATAdvancedMachiningInterfaces \
						ProductStructurePubIDL \
						CATTessellation CATAdvancedMathematics \
						CATTPSItfCPP  \
						CATJNIAnnotationTypeLib \
						CATTPSProIDL \
						CATTPSPubIDL \
						CATTPSUUID \
						JS0GROUP JS0FM \
						CATPartInterfaces \
						CATSketcherInterfaces \
						CATVisualization \
            CATGeometricOperators \
			CATProductStructure1  \
			CATMathStream \
			CATSaiSpaceAnalysisItf \
			JS0SCBAK \
			SimulationItf \
			CATMechanicalModelerUI  \
			CATMechanicalModeler \
            CATProductStructure1          \
            CATTTRSItf                    \
            CATTTRSUUID                   \
            CATInteractiveInterfaces  \ 
            CATTPSUUID                    \
            CATMathStream                 \
            CATCGMGeoMath                 \
           CATTopologicalObjects \ 
DI0PANV2  \
CATMathematics CATDialogEngine 	 \
ApplicationFrame CATAfrUUID  \
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
