// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// TrainAddin.cpp
// Provide implementation to interface
//    CATIAfrGeneralWksAddin
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Jan 2015  Creation: Code generated by the CAA wizard  ALI
//===================================================================
#include "TrainAddin.h"
 
CATImplementClass(TrainAddin,
                  Implementation,
                  CATBaseUnknown,
                  CATnull );
 
MacDeclareHeader(TrainHeader);
//-----------------------------------------------------------------------------
// TrainAddin : constructor
//-----------------------------------------------------------------------------
TrainAddin::TrainAddin():
    CATBaseUnknown()
{

}

//-----------------------------------------------------------------------------
// TrainAddin : destructor
//-----------------------------------------------------------------------------
TrainAddin::~TrainAddin()
{
}
 
// Link the implementation to its interface
// ---------------------------------------



//TIE or TIEchain definitions
#include "TIE_CATIAfrGeneralWksAddin.h"
TIE_CATIAfrGeneralWksAddin(TrainAddin);


//Methods implementation

void TrainAddin::CreateCommands()
{
	//此语句用于将command与工具条联系起来
	//参数：菜单名
	//参数：菜单相应的命令所在的模块名
	//参数：插入的命令名
	new TrainHeader("TrainHdr", "TrainModuleCmd", "FirstDlgCmd", (void*)NULL);
	new TrainHeader("TrainSndHdr", "TrainModuleCmd", "BITCreateAssemSndCmd", (void*)NULL);
	new TrainHeader("取点", "AxisPointCmd", "AxisDlgCmd", (void*)NULL);
    new TrainHeader("点生成", "PointCmd", "PointDlgCmd", (void*)NULL);
	new TrainHeader("测试", "SwapTextM", "MyPraTranscmd", (void*)NULL);
	new TrainHeader("Pad生成", "PadCmd", "PadDlgCmd", (void*)NULL);
	new TrainHeader("导入文件", "AddDocCmd", "AddDocCmd", (void*)NULL);
	new TrainHeader("提取管路特征", "ExtractFeatureM", "ExtractfeatureCmd", (void*)NULL);
	new TrainHeader("余量计算", "CalculateAllowanceM", "CalculateAllowanceCmd", (void*)NULL);
}
CATCmdContainer * TrainAddin::CreateToolbars()
{
	//1。添加工具条
	NewAccess(CATCmdContainer,pCAAPMSTlb,CAAPMSTlb);	
		
		//2.1。添加按钮.
		NewAccess(CATCmdStarter, pCAATPMSCreateLineStr, CAATPMSCreateLineStr);
		//2.2。给按钮关联命令
		SetAccessCommand(pCAATPMSCreateLineStr,"TrainHdr");
		//2.3。将按钮添加至工具条中
		SetAccessChild(pCAAPMSTlb,pCAATPMSCreateLineStr);

		//3.1。添加按钮
		NewAccess(CATCmdStarter, pCAATPMSCreateLineSndStr, CAATPMSCreateLineSndStr);
		//3.2。给按钮关联命令
		SetAccessCommand(pCAATPMSCreateLineSndStr,"TrainSndHdr");
		//3.3。将按钮添加至工具条中
		SetAccessNext(pCAATPMSCreateLineStr, pCAATPMSCreateLineSndStr);
	
		NewAccess(CATCmdStarter, pCAATPMSCreateLineThrStr, CAATPMSCreateLineThrStr);
		SetAccessCommand(pCAATPMSCreateLineThrStr,"取点");
		SetAccessNext(pCAATPMSCreateLineSndStr, pCAATPMSCreateLineThrStr);

		NewAccess(CATCmdStarter, pCAATPMSCreateLineForStr, CAATPMSCreateLineForStr);
		SetAccessCommand(pCAATPMSCreateLineForStr,"Pad生成");
		SetAccessNext(pCAATPMSCreateLineThrStr, pCAATPMSCreateLineForStr);

		NewAccess(CATCmdStarter, pCAATPMSCreateLineFifStr, CAATPMSCreateLineFifStr);
		SetAccessCommand(pCAATPMSCreateLineFifStr,"点生成");
		SetAccessNext(pCAATPMSCreateLineForStr, pCAATPMSCreateLineFifStr);

		NewAccess(CATCmdStarter, pCAATPMSCreateLineSixStr, CAATPMSCreateLineSixStr);
		SetAccessCommand(pCAATPMSCreateLineSixStr,"测试");
		SetAccessNext(pCAATPMSCreateLineFifStr, pCAATPMSCreateLineSixStr);

		NewAccess(CATCmdStarter, pCAATPMSCreateLineSevStr, CAATPMSCreateLineSevStr);
		SetAccessCommand(pCAATPMSCreateLineSevStr,"导入文件");
		SetAccessNext(pCAATPMSCreateLineSixStr, pCAATPMSCreateLineSevStr);

		NewAccess(CATCmdStarter, pCAATPMSCreateLineEigStr, CAATPMSCreateLineEigStr);
		SetAccessCommand(pCAATPMSCreateLineEigStr,"提取管路特征");
		SetAccessNext(pCAATPMSCreateLineSevStr, pCAATPMSCreateLineEigStr);

		NewAccess(CATCmdStarter, pCAATPMSCreateLineNinStr, CAATPMSCreateLineNinStr);
		SetAccessCommand(pCAATPMSCreateLineNinStr,"余量计算");
		SetAccessNext(pCAATPMSCreateLineEigStr, pCAATPMSCreateLineNinStr);
	//4。将工具条添加到视窗中
	AddToolbarView(pCAAPMSTlb,1,Right);


	//1. 添加菜单
	NewAccess(CATCmdContainer,pCAAPMSMnu,CAAPMSMnu);
		//添加菜单窗口
		NewAccess(CATCmdContainer,pCATAssemMnu, CATAssemMnu); 
		SetAccessChild(pCAAPMSMnu,pCATAssemMnu);	
			//2.添加菜单项
			NewAccess(CATCmdStarter,pCAATPMuAixsAutoStr,CAATPMuAixsAutoStr);
			SetAccessCommand(pCAATPMuAixsAutoStr,"TrainHdr");
			SetAccessChild(pCATAssemMnu,pCAATPMuAixsAutoStr);

			//3.添加菜单项
			NewAccess(CATCmdStarter,pCAATPMuAixsAutoSndStr,CAATPMuAixsAutoSndStr);
			SetAccessCommand(pCAATPMuAixsAutoSndStr,"TrainSndHdr");
			SetAccessNext(pCAATPMuAixsAutoStr,pCAATPMuAixsAutoSndStr);

			NewAccess(CATCmdStarter,pCAATPMuAixsAutoThrStr,CAATPMuAixsAutoThrStr);
			SetAccessCommand(pCAATPMuAixsAutoThrStr,"取点");
			SetAccessNext(pCAATPMuAixsAutoSndStr,pCAATPMuAixsAutoThrStr);

			NewAccess(CATCmdStarter,pCAATPMuAixsAutoForStr,CAATPMuAixsAutoForStr);
			SetAccessCommand(pCAATPMuAixsAutoForStr,"Pad生成");
			SetAccessNext(pCAATPMuAixsAutoThrStr,pCAATPMuAixsAutoForStr);

			NewAccess(CATCmdStarter,pCAATPMuAixsAutoFifStr,CAATPMuAixsAutoFifStr);
			SetAccessCommand(pCAATPMuAixsAutoFifStr,"点生成");
			SetAccessNext(pCAATPMuAixsAutoForStr,pCAATPMuAixsAutoFifStr);

			NewAccess(CATCmdStarter,pCAATPMuAixsAutoSixStr,CAATPMuAixsAutoSixStr);
			SetAccessCommand(pCAATPMuAixsAutoSixStr,"测试");
			SetAccessNext(pCAATPMuAixsAutoFifStr,pCAATPMuAixsAutoSixStr);

			NewAccess(CATCmdStarter,pCAATPMuAixsAutoSevStr,CAATPMuAixsAutoSevStr);
			SetAccessCommand(pCAATPMuAixsAutoSevStr,"导入文件");
			SetAccessNext(pCAATPMuAixsAutoSixStr,pCAATPMuAixsAutoSevStr);

			NewAccess(CATCmdStarter,pCAATPMuAixsAutoEigStr,CAATPMuAixsAutoEigStr);
			SetAccessCommand(pCAATPMuAixsAutoEigStr,"提取管路特征");
			SetAccessNext(pCAATPMuAixsAutoSevStr,pCAATPMuAixsAutoEigStr);

			NewAccess(CATCmdStarter,pCAATPMuAixsAutoNinStr,CAATPMuAixsAutoNinStr);
			SetAccessCommand(pCAATPMuAixsAutoNinStr,"余量计算");
			SetAccessNext(pCAATPMuAixsAutoEigStr,pCAATPMuAixsAutoNinStr);

		NewAccess(CATCmdSeparator, pCAATPMSCreateLineSepratorStr, CAATPMSCreateLineSepratorStr);
		SetAccessNext(pCAATPMuAixsAutoSndStr, pCAATPMSCreateLineSepratorStr);
		SetAccessNext(pCAATPMSCreateLineSepratorStr, pCAATPMuAixsAutoThrStr);

	//4.将菜单和工具条关联
	SetAddinMenu(pCAAPMSTlb,pCAAPMSMnu);

	//Attach the menu bar to the workbench
	return pCAAPMSTlb;
}	
