// COPYRIGHT Dassault Systemes 2012
//===================================================================
//
// BITCreateAssemSndCmd.cpp
// The command: BITCreateAssemSndCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Jul 2012  Creation: Code generated by the CAA wizard  ali
//===================================================================
#include "BITCreateAssemSndCmd.h"
#include "BITCreateAssemSndDlg.h"
#include "CATCreateExternalObject.h"
CATCreateClass( BITCreateAssemSndCmd);


//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
BITCreateAssemSndCmd::BITCreateAssemSndCmd() :
  CATCommand (NULL, "BITCreateAssemSndCmd")
{
  RequestStatusChange (CATCommandMsgRequestExclusiveMode);
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
BITCreateAssemSndCmd::~BITCreateAssemSndCmd()
{
}


//  Overload this method: when your command gains focus
//
// Activates a command.
//   iFromClient :The command that requests to activate the current one.
//   iEvtDat :The notification sent.
// ----------------------------------------------------
CATStatusChangeRC BITCreateAssemSndCmd::Activate( CATCommand * iFromClient, CATNotification * iEvtDat)
{
	//命令响应菜单的单击操作，执行所需的命令
	BITCreateAssemSndDlg* pDlg = new BITCreateAssemSndDlg();
	pDlg->Build();
	pDlg->SetVisibility(CATDlgShow);
  RequestDelayedDestruction();

	return (CATStatusChangeRCCompleted);
}

//  Overload this method: when your command loses focus
//
// Deactivates a command.
//   iFromClient :The command that requests to activate the current one.
//   iEvtDat :The notification sent.
// ----------------------------------------------------
CATStatusChangeRC BITCreateAssemSndCmd::Desactivate( CATCommand * iFromClient, CATNotification * iEvtDat)
{
  return (CATStatusChangeRCCompleted);
}

//  Overload this method: when your command is canceled
//
// Cancel a command.
//   iFromClient :The command that requests to activate the current one.
//   iEvtDat :The notification sent.
// ----------------------------------------------------
CATStatusChangeRC BITCreateAssemSndCmd::Cancel( CATCommand * iFromClient, CATNotification * iEvtDat)
{
  RequestDelayedDestruction();
  return (CATStatusChangeRCCompleted);
}
