// COPYRIGHT Dassault Systemes 2012
//===================================================================
//
// BITCreateAssemSndDlg.cpp
// The dialog : BITCreateAssemSndDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Jul 2012  Creation: Code generated by the CAA wizard  ali
//===================================================================
#include "BITCreateAssemSndDlg.h"
#include "CATDlgRadioButton.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#include "CATDlgNotify.h"		//massage window用的头文件
#include "CATUnicodeString.h"	//对字符串操作时用的头文件
#include "CATDlgMultiList.h"	//对MultiList操作时用的头文件
#include <math.h>

#ifdef BITCreateAssemSndDlg_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif




//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
BITCreateAssemSndDlg::BITCreateAssemSndDlg() :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"BITCreateAssemSndDlg",CATDlgWndNoButton|CATDlgGridLayout
//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
                               )
{
//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
 _Frame037 = NULL;
 _Label039 = NULL;
 _EditorL01 = NULL;
 _Label041 = NULL;
 _Label042 = NULL;
 _EditorL02 = NULL;
 _Label044 = NULL;
 _Label045 = NULL;
 _EditorL03 = NULL;
 _Label047 = NULL;
 _PushButtonL02 = NULL;
 _Label051 = NULL;
 _EditorL05 = NULL;
 _Label054 = NULL;
 _Label067 = NULL;
 _EditorL04 = NULL;
 _Label069 = NULL;
 _PushButtonL01 = NULL;
 _Label092 = NULL;
 _EditorCD = NULL;
 _Label094 = NULL;
 _Frame098 = NULL;
 _Label099 = NULL;
 _Frame055 = NULL;
 _Label058 = NULL;
 _Frame072 = NULL;
 _Label064 = NULL;
 _EditorFB = NULL;
 _Label066 = NULL;
 _Label073 = NULL;
 _EditorJZ = NULL;
 _Label075 = NULL;
 _PushButtonL03 = NULL;
 _Label078 = NULL;
 _EditorZA = NULL;
 _Label080 = NULL;
 _Label081 = NULL;
 _EditorZB = NULL;
 _Label083 = NULL;
 _Label084 = NULL;
 _EditorND = NULL;
 _Label086 = NULL;
 _LabelWZ = NULL;
 _EditorWZ = NULL;
 _Label091 = NULL;
 _ComboXS = NULL;
 _Frame095 = NULL;
 _Label096 = NULL;
 _Frame100 = NULL;
 _Label101 = NULL;
 _RadioButton102 = NULL;
 _RadioButton103 = NULL;
 _Label104 = NULL;
 _Editor105 = NULL;
 _Label106 = NULL;
 _Editor107 = NULL;
 _Label108 = NULL;
 _Label109 = NULL;
 _Editor110 = NULL;
 _Editor111 = NULL;
 _PushButtonJH = NULL;
 _Label113 = NULL;
 _Label114 = NULL;
 _Label115 = NULL;
 _Label117 = NULL;
//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
BITCreateAssemSndDlg::~BITCreateAssemSndDlg()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _Frame037 = NULL;
 _Label039 = NULL;
 _EditorL01 = NULL;
 _Label041 = NULL;
 _Label042 = NULL;
 _EditorL02 = NULL;
 _Label044 = NULL;
 _Label045 = NULL;
 _EditorL03 = NULL;
 _Label047 = NULL;
 _PushButtonL02 = NULL;
 _Label051 = NULL;
 _EditorL05 = NULL;
 _Label054 = NULL;
 _Label067 = NULL;
 _EditorL04 = NULL;
 _Label069 = NULL;
 _PushButtonL01 = NULL;
 _Label092 = NULL;
 _EditorCD = NULL;
 _Label094 = NULL;
 _Frame098 = NULL;
 _Label099 = NULL;
 _Frame055 = NULL;
 _Label058 = NULL;
 _Frame072 = NULL;
 _Label064 = NULL;
 _EditorFB = NULL;
 _Label066 = NULL;
 _Label073 = NULL;
 _EditorJZ = NULL;
 _Label075 = NULL;
 _PushButtonL03 = NULL;
 _Label078 = NULL;
 _EditorZA = NULL;
 _Label080 = NULL;
 _Label081 = NULL;
 _EditorZB = NULL;
 _Label083 = NULL;
 _Label084 = NULL;
 _EditorND = NULL;
 _Label086 = NULL;
 _LabelWZ = NULL;
 _EditorWZ = NULL;
 _Label091 = NULL;
 _ComboXS = NULL;
 _Frame095 = NULL;
 _Label096 = NULL;
 _Frame100 = NULL;
 _Label101 = NULL;
 _RadioButton102 = NULL;
 _RadioButton103 = NULL;
 _Label104 = NULL;
 _Editor105 = NULL;
 _Label106 = NULL;
 _Editor107 = NULL;
 _Label108 = NULL;
 _Label109 = NULL;
 _Editor110 = NULL;
 _Editor111 = NULL;
 _PushButtonJH = NULL;
 _Label113 = NULL;
 _Label114 = NULL;
 _Label115 = NULL;
 _Label117 = NULL;
//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
}



void BITCreateAssemSndDlg::Build()
{
//  TODO: This call builds your dialog from the layout declaration file
//  -------------------------------------------------------------------

//CAA2 WIZARD WIDGET CONSTRUCTION SECTION
 _Frame037 = new CATDlgFrame(this, "Frame037", CATDlgGridLayout);
_Frame037 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Label039 = new CATDlgLabel(_Frame037, "Label039");
_Label039 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _EditorL01 = new CATDlgEditor(_Frame037, "EditorL01", CATDlgEdtDouble);
 _EditorL01 -> SetPrecision( 0 );
_EditorL01 -> SetGridConstraints(1, 1, 1, 1, CATGRID_4SIDES);
 _Label041 = new CATDlgLabel(_Frame037, "Label041");
_Label041 -> SetGridConstraints(1, 2, 1, 1, CATGRID_4SIDES);
 _Label042 = new CATDlgLabel(_Frame037, "Label042");
_Label042 -> SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);
 _EditorL02 = new CATDlgEditor(_Frame037, "EditorL02", CATDlgEdtDouble);
 _EditorL02 -> SetPrecision( 0 );
_EditorL02 -> SetGridConstraints(2, 1, 1, 1, CATGRID_4SIDES);
 _Label044 = new CATDlgLabel(_Frame037, "Label044");
_Label044 -> SetGridConstraints(2, 2, 1, 1, CATGRID_4SIDES);
 _Label045 = new CATDlgLabel(_Frame037, "Label045");
_Label045 -> SetGridConstraints(3, 0, 1, 1, CATGRID_4SIDES);
 _EditorL03 = new CATDlgEditor(_Frame037, "EditorL03", CATDlgEdtDouble);
 _EditorL03 -> SetPrecision( 0 );
_EditorL03 -> SetGridConstraints(3, 1, 1, 1, CATGRID_4SIDES);
 _Label047 = new CATDlgLabel(_Frame037, "Label047");
_Label047 -> SetGridConstraints(3, 2, 1, 1, CATGRID_4SIDES);
 _PushButtonL02 = new CATDlgPushButton(_Frame037, "PushButtonL02");
_PushButtonL02 -> SetGridConstraints(6, 0, 2, 1, CATGRID_4SIDES);
 _Label051 = new CATDlgLabel(_Frame037, "Label051");
_Label051 -> SetGridConstraints(7, 0, 1, 1, CATGRID_4SIDES);
 _EditorL05 = new CATDlgEditor(_Frame037, "EditorL05", CATDlgEdtDouble);
 _EditorL05 -> SetVisibleTextHeight(3);
 _EditorL05 -> SetPrecision( 0 );
_EditorL05 -> SetGridConstraints(7, 1, 1, 1, CATGRID_4SIDES);
 _Label054 = new CATDlgLabel(_Frame037, "Label054");
_Label054 -> SetGridConstraints(7, 2, 1, 1, CATGRID_4SIDES);
 _Label067 = new CATDlgLabel(_Frame037, "Label067");
_Label067 -> SetGridConstraints(5, 0, 1, 1, CATGRID_4SIDES);
 _EditorL04 = new CATDlgEditor(_Frame037, "EditorL04", CATDlgEdtDouble);
 _EditorL04 -> SetPrecision( 0 );
_EditorL04 -> SetGridConstraints(5, 1, 1, 1, CATGRID_4SIDES);
 _Label069 = new CATDlgLabel(_Frame037, "Label069");
_Label069 -> SetGridConstraints(5, 2, 1, 1, CATGRID_4SIDES);
 _PushButtonL01 = new CATDlgPushButton(_Frame037, "PushButtonL01");
_PushButtonL01 -> SetGridConstraints(0, 0, 2, 1, CATGRID_4SIDES);
 _Label092 = new CATDlgLabel(_Frame037, "Label092");
_Label092 -> SetGridConstraints(4, 0, 1, 1, CATGRID_4SIDES);
 _EditorCD = new CATDlgEditor(_Frame037, "EditorCD", CATDlgEdtDouble);
 _EditorCD -> SetPrecision( 0 );
_EditorCD -> SetGridConstraints(4, 1, 1, 1, CATGRID_4SIDES);
 _Label094 = new CATDlgLabel(_Frame037, "Label094");
_Label094 -> SetGridConstraints(4, 2, 1, 1, CATGRID_4SIDES);
 _Frame098 = new CATDlgFrame(_Frame037, "Frame098", CATDlgGridLayout);
_Frame098 -> SetGridConstraints(0, 3, 1, 8, CATGRID_4SIDES);
 _Label099 = new CATDlgLabel(_Frame098, "Label099");
_Label099 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Frame055 = new CATDlgFrame(this, "Frame055", CATDlgGridLayout);
_Frame055 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _Label058 = new CATDlgLabel(_Frame055, "Label058");
_Label058 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Frame072 = new CATDlgFrame(_Frame055, "Frame072", CATDlgFraNoTitle|CATDlgGridLayout);
_Frame072 -> SetGridConstraints(1, 1, 1, 1, CATGRID_4SIDES);
 _Label064 = new CATDlgLabel(_Frame072, "Label064");
_Label064 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _EditorFB = new CATDlgEditor(_Frame072, "EditorFB", CATDlgEdtDouble);
 _EditorFB -> SetPrecision( 0 );
_EditorFB -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _Label066 = new CATDlgLabel(_Frame072, "Label066");
_Label066 -> SetGridConstraints(0, 2, 1, 1, CATGRID_4SIDES);
 _Label073 = new CATDlgLabel(_Frame072, "Label073");
_Label073 -> SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);
 _EditorJZ = new CATDlgEditor(_Frame072, "EditorJZ", CATDlgEdtDouble);
 _EditorJZ -> SetPrecision( 0 );
_EditorJZ -> SetGridConstraints(2, 1, 1, 1, CATGRID_4SIDES);
 _Label075 = new CATDlgLabel(_Frame072, "Label075");
_Label075 -> SetGridConstraints(2, 2, 1, 1, CATGRID_4SIDES);
 _PushButtonL03 = new CATDlgPushButton(_Frame072, "PushButtonL03");
_PushButtonL03 -> SetGridConstraints(3, 0, 3, 1, CATGRID_4SIDES);
 _Label078 = new CATDlgLabel(_Frame072, "Label078");
_Label078 -> SetGridConstraints(4, 0, 1, 1, CATGRID_4SIDES);
 _EditorZA = new CATDlgEditor(_Frame072, "EditorZA", CATDlgEdtDouble);
 _EditorZA -> SetPrecision( 0 );
_EditorZA -> SetGridConstraints(4, 1, 1, 1, CATGRID_4SIDES);
 _Label080 = new CATDlgLabel(_Frame072, "Label080");
_Label080 -> SetGridConstraints(4, 2, 1, 1, CATGRID_4SIDES);
 _Label081 = new CATDlgLabel(_Frame072, "Label081");
_Label081 -> SetGridConstraints(5, 0, 1, 1, CATGRID_4SIDES);
 _EditorZB = new CATDlgEditor(_Frame072, "EditorZB", CATDlgEdtDouble);
 _EditorZB -> SetPrecision( 0 );
_EditorZB -> SetGridConstraints(5, 1, 1, 1, CATGRID_4SIDES);
 _Label083 = new CATDlgLabel(_Frame072, "Label083");
_Label083 -> SetGridConstraints(5, 2, 1, 1, CATGRID_4SIDES);
 _Label084 = new CATDlgLabel(_Frame072, "Label084");
_Label084 -> SetGridConstraints(6, 0, 1, 1, CATGRID_4SIDES);
 _EditorND = new CATDlgEditor(_Frame072, "EditorND", CATDlgEdtDouble);
 _EditorND -> SetPrecision( 0 );
_EditorND -> SetGridConstraints(6, 1, 1, 1, CATGRID_4SIDES);
 _Label086 = new CATDlgLabel(_Frame072, "Label086");
_Label086 -> SetGridConstraints(6, 2, 1, 1, CATGRID_4SIDES);
 _LabelWZ = new CATDlgLabel(_Frame072, "LabelWZ");
_LabelWZ -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _EditorWZ = new CATDlgEditor(_Frame072, "EditorWZ", CATDlgEdtDouble);
 _EditorWZ -> SetPrecision( 0 );
_EditorWZ -> SetGridConstraints(1, 1, 1, 1, CATGRID_4SIDES);
 _Label091 = new CATDlgLabel(_Frame072, "Label091");
_Label091 -> SetGridConstraints(1, 2, 1, 1, CATGRID_4SIDES);
 _ComboXS = new CATDlgCombo(_Frame055, "ComboXS");
_ComboXS -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _Frame095 = new CATDlgFrame(this, "Frame095", CATDlgGridLayout);
_Frame095 -> SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);
 _Label096 = new CATDlgLabel(_Frame095, "Label096", CATDlgLabCenter);
_Label096 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Frame100 = new CATDlgFrame(this, "Frame100", CATDlgGridLayout);
_Frame100 -> SetGridConstraints(3, 0, 1, 1, CATGRID_4SIDES);
 _Label101 = new CATDlgLabel(_Frame100, "Label101");
_Label101 -> SetGridConstraints(0, 0, 1, 6, CATGRID_4SIDES);
 _RadioButton102 = new CATDlgRadioButton(_Frame100, "RadioButton102");
_RadioButton102 -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _RadioButton103 = new CATDlgRadioButton(_Frame100, "RadioButton103");
_RadioButton103 -> SetGridConstraints(0, 2, 1, 1, CATGRID_4SIDES);
 _Label104 = new CATDlgLabel(_Frame100, "Label104");
_Label104 -> SetGridConstraints(1, 1, 1, 1, CATGRID_4SIDES);
 _Editor105 = new CATDlgEditor(_Frame100, "Editor105", CATDlgEdtDouble);
 _Editor105 -> SetPrecision( 0 );
_Editor105 -> SetGridConstraints(1, 2, 1, 1, CATGRID_4SIDES);
 _Label106 = new CATDlgLabel(_Frame100, "Label106");
_Label106 -> SetGridConstraints(2, 1, 1, 1, CATGRID_4SIDES);
 _Editor107 = new CATDlgEditor(_Frame100, "Editor107", CATDlgEdtDouble);
 _Editor107 -> SetPrecision( 0 );
_Editor107 -> SetGridConstraints(2, 2, 1, 1, CATGRID_4SIDES);
 _Label108 = new CATDlgLabel(_Frame100, "Label108");
_Label108 -> SetGridConstraints(3, 1, 1, 1, CATGRID_4SIDES);
 _Label109 = new CATDlgLabel(_Frame100, "Label109");
_Label109 -> SetGridConstraints(4, 1, 1, 1, CATGRID_4SIDES);
 _Editor110 = new CATDlgEditor(_Frame100, "Editor110", CATDlgEdtDouble);
 _Editor110 -> SetPrecision( 0 );
_Editor110 -> SetGridConstraints(3, 2, 1, 1, CATGRID_4SIDES);
 _Editor111 = new CATDlgEditor(_Frame100, "Editor111", CATDlgEdtDouble);
 _Editor111 -> SetPrecision( 0 );
_Editor111 -> SetGridConstraints(4, 2, 1, 1, CATGRID_4SIDES);
 _PushButtonJH = new CATDlgPushButton(_Frame100, "PushButtonJH");
_PushButtonJH -> SetGridConstraints(5, 1, 2, 1, CATGRID_4SIDES);
 _Label113 = new CATDlgLabel(_Frame100, "Label113");
_Label113 -> SetGridConstraints(1, 3, 1, 1, CATGRID_4SIDES);
 _Label114 = new CATDlgLabel(_Frame100, "Label114");
_Label114 -> SetGridConstraints(2, 3, 1, 1, CATGRID_4SIDES);
 _Label115 = new CATDlgLabel(_Frame100, "Label115");
_Label115 -> SetGridConstraints(3, 3, 1, 1, CATGRID_4SIDES);
 _Label117 = new CATDlgLabel(_Frame100, "Label117");
_Label117 -> SetGridConstraints(4, 3, 1, 1, CATGRID_4SIDES);
//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION
//初始化Selector
  _ComboXS -> ClearLine();
  _ComboXS -> SetLine("情境一",0,CATDlgDataAdd);
  _ComboXS -> SetLine("情境二",1,CATDlgDataAdd);
  _ComboXS -> SetLine("情境三",2,CATDlgDataAdd);
  _ComboXS -> SetLine("情境四",3,CATDlgDataAdd);
  _ComboXS -> SetSelect(0);

///////////////////////////

//CAA2 WIZARD CALLBACK DECLARATION SECTION
     AddAnalyseNotificationCB (_PushButtonJH, 
                               _PushButtonJH->GetPushBActivateNotification(),
                               (CATCommandMethod)&BITCreateAssemSndDlg::OnPushButtonJHPushBActivateNotification,
                               NULL);
     AddAnalyseNotificationCB (_ComboXS, 
                               _ComboXS->GetComboSelectNotification(),
                               (CATCommandMethod)&BITCreateAssemSndDlg::OnComboXSComboSelectNotification,
                               NULL);
     AddAnalyseNotificationCB (_PushButtonL03, 
                               _PushButtonL03->GetPushBActivateNotification(),
                               (CATCommandMethod)&BITCreateAssemSndDlg::OnPushButtonL03PushBActivateNotification,
                               NULL);
     AddAnalyseNotificationCB (_PushButtonL02, 
                               _PushButtonL02->GetPushBActivateNotification(),
                               (CATCommandMethod)&BITCreateAssemSndDlg::OnPushButtonL02PushBActivateNotification,
                               NULL);
     AddAnalyseNotificationCB (_PushButtonL01, 
                               _PushButtonL01->GetPushBActivateNotification(),
                               (CATCommandMethod)&BITCreateAssemSndDlg::OnPushButtonL01PushBActivateNotification,
                               NULL);
     AddAnalyseNotificationCB (this, 
                               GetWindCloseNotification(),
                               (CATCommandMethod)&BITCreateAssemSndDlg::OnBITCreateAssemSndDlgWindCloseNotification,
                               NULL);

 _Label099 -> SetIconName("GXJ.bmp");
 _Label101 -> SetIconName("LS.bmp");
	 
}
//-------------------------------------------------------------------------
// Callback on WindClose of _BITCreateAssemSndDlg
//-------------------------------------------------------------------------
void BITCreateAssemSndDlg::OnBITCreateAssemSndDlgWindCloseNotification(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
    this->SetVisibility(CATDlgHide);
	this->RequestDelayedDestruction();

}


//-------------------------------------------------------------------------
// Callback on PushBActivate of _PushButtonL01
//-------------------------------------------------------------------------
void BITCreateAssemSndDlg::OnPushButtonL01PushBActivateNotification(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
  _EditorL01 ->SetValue(250,1);
  _EditorL02 ->SetValue(250,1);
  _EditorL03 ->SetValue(10,1);
  _EditorL04 ->SetValue(200,1);
  _EditorCD ->SetValue(6000,1);
}


//-------------------------------------------------------------------------
// Callback on PushBActivate of _PushButtonL02
//-------------------------------------------------------------------------
void BITCreateAssemSndDlg::OnPushButtonL02PushBActivateNotification(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
  double Cauh,Caub,Caut,CauE,CauI;
  Cauh =  _EditorL01 ->GetValue();
  Caub =  _EditorL02 ->GetValue();
  Caut =  _EditorL03 ->GetValue();
  CauE =  _EditorL04 ->GetValue();
  CauI = (Caub*Cauh*Cauh*Cauh)/12 - ((Caub-2*Caut)*(Cauh-2*Caut)*(Cauh-2*Caut)*(Cauh-2*Caut))/12;
  _EditorL05 ->SetValue(CauI,1);
}


//-------------------------------------------------------------------------
// Callback on Create of _SelectorList063
//-------------------------------------------------------------------------



//-------------------------------------------------------------------------
// Callback on PushBActivate of _PushButtonL03
//-------------------------------------------------------------------------
void BITCreateAssemSndDlg::OnPushButtonL03PushBActivateNotification(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
  int LineSelected = _ComboXS -> GetSelect();
//悬臂梁集中载荷
  if(LineSelected == 0)
  {
	  double CAUb,CAUl,CAUP,CAUE,CAUI,CAUx ;
	  CAUb = _EditorWZ ->GetValue();
	  CAUl = _EditorCD ->GetValue();
	  CAUP = _EditorJZ ->GetValue();
	  CAUE = _EditorL04 ->GetValue();
	  CAUI = _EditorL05 ->GetValue();

	  _EditorZA -> SetValue(0,1);
	  _EditorZB -> SetValue(CAUP,1);
//计算挠度值
	  CAUx = (((CAUP*CAUb*CAUb*CAUl)/(2*CAUE*CAUI))*(3-CAUb/CAUl))/1000;
	  _EditorND -> SetValue(CAUx,1);
		

  }
//悬臂梁分布载荷
  if(LineSelected == 1)
  {
	  double CAUl,CAUq,CAUE,CAUI,CAUx ;
	  CAUl = _EditorCD ->GetValue();
	  CAUq = _EditorFB ->GetValue();
	  CAUE = _EditorL04 ->GetValue();
	  CAUI = _EditorL05 ->GetValue();

	  _EditorZA -> SetValue(0,1);
	  _EditorZB -> SetValue(CAUq*CAUl,1);
//计算挠度值
	  CAUx = ((CAUq*CAUl*CAUl*CAUl*CAUl)/(8*CAUE*CAUI))/1000;
	  _EditorND -> SetValue(CAUx,1);	
  }
//简支梁集中载荷
  if(LineSelected == 2)
  {
	  double CAUl,CAUP,CAUE,CAUI,CAUx ;
	  CAUl = _EditorCD ->GetValue();
	  CAUP = _EditorJZ ->GetValue();
	  CAUE = _EditorL04 ->GetValue();
	  CAUI = _EditorL05 ->GetValue();

	  _EditorZA -> SetValue(CAUP/2,1);
	  _EditorZB -> SetValue(CAUP/2,1);
//计算挠度值
	  CAUx = ((CAUP*CAUl*CAUl*CAUl)/(48*CAUE*CAUI))/1000;
	  _EditorND -> SetValue(CAUx,1);
		

  }
  if(LineSelected == 3)
  {
	  double CAUl,CAUq,CAUE,CAUI,CAUx ;
	  CAUl = _EditorCD ->GetValue();
	  CAUq = _EditorFB ->GetValue();
	  CAUE = _EditorL04 ->GetValue();
	  CAUI = _EditorL05 ->GetValue();

	  _EditorZA -> SetValue(CAUq*CAUl/2,1);
	  _EditorZB -> SetValue(CAUq*CAUl/2,1);
//计算挠度值
	  CAUx = ((5*CAUq*CAUl*CAUl*CAUl*CAUl)/(384*CAUE*CAUI))/1000;
	  _EditorND -> SetValue(CAUx,1);	
  }
}


//-------------------------------------------------------------------------
// Callback on ComboSelect of _ComboXS
//-------------------------------------------------------------------------
void BITCreateAssemSndDlg::OnComboXSComboSelectNotification(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{

  int LineSelected = _ComboXS -> GetSelect();
  if(LineSelected == 0 )
  {

	  _EditorJZ -> SetValue(1,1);
 	  _EditorWZ -> SetValue(1,1);
	  _EditorZA -> SetValue(0,1);
      _EditorZB -> SetValue(0,1);
      _EditorND -> SetValue(0,1);
	  _EditorFB -> SetValue(0,1);
	  _Label096->SetIconName("ST1.bmp");

  }
  if(LineSelected == 1)
  {

	  _EditorJZ -> SetValue(0,1);
 	  _EditorWZ -> SetValue(0,1);
	  _EditorZA -> SetValue(0,1);
      _EditorZB -> SetValue(0,1);
      _EditorND -> SetValue(0,1);
	  _EditorFB -> SetValue(1,1);
	   _Label096->SetIconName("ST2.bmp");

  }
  if(LineSelected == 2 )
  {

	  double CAUl;
	  CAUl = _EditorCD ->GetValue();
	  _EditorJZ -> SetValue(1,1);
	  _EditorZA -> SetValue(0,1);
      _EditorZB -> SetValue(0,1);
      _EditorND -> SetValue(0,1);
	  _EditorFB -> SetValue(0,1);
	  _EditorWZ -> SetValue(CAUl/2,1);
	   _Label096->SetIconName("ST3.bmp");

  }
  if(LineSelected == 3)
  {
	  _EditorJZ -> SetValue(0,1);
 	  _EditorWZ -> SetValue(0,1);
	  _EditorZA -> SetValue(0,1);
      _EditorZB -> SetValue(0,1);
      _EditorND -> SetValue(0,1);
	  _EditorFB -> SetValue(1,1);
	   _Label096->SetIconName("ST4.bmp");

  }


}


//-------------------------------------------------------------------------
// Callback on PushBActivate of _PushButtonJH
//-------------------------------------------------------------------------
void BITCreateAssemSndDlg::OnPushButtonJHPushBActivateNotification(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
  CATULong ButtonStateA = _RadioButton102 -> GetState();
  CATULong ButtonStateB = _RadioButton103 -> GetState();
  if(ButtonStateA == CATDlgCheck )
  {
	double NegOne = -1;
	_Editor105 -> SetValue(130.73,1);
	double ReaFor = _EditorZA ->GetValue();
	double Fv = ReaFor/0.6;
	double ReaStress = (Fv/(acos(NegOne)*0.014*0.014))/1000000;
    _Editor107 -> SetValue(ReaStress,1);
	_Editor110 -> SetValue(65.37,1);
	_Editor111 -> SetValue(ReaStress/2,1);
  }
  if(ButtonStateB == CATDlgCheck )
  {
	  double NegOne = -1;
	  _Editor105 -> SetValue(130.73,1);
	  double ReaFor = _EditorZB ->GetValue();
	  double Fv = ReaFor/0.6;
	  double ReaStress = (Fv/(acos(NegOne)*0.014*0.014))/1000000;
		  _Editor107 -> SetValue(ReaStress,1);
	  _Editor110 -> SetValue(65.37,1);
	  _Editor111 -> SetValue(ReaStress/2,1);
  }
}

