// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// FirstDlgCmd.cpp
// The command: FirstDlgCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Jan 2015  Creation: Code generated by the CAA wizard  ALI
//===================================================================
#include "FirstDlgCmd.h"
#include "FirstDlg.h"

#include "CATCreateExternalObject.h"
CATCreateClass( FirstDlgCmd);


//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
FirstDlgCmd::FirstDlgCmd() :
  CATCommand (NULL, "FirstDlgCmd")
{
  RequestStatusChange (CATCommandMsgRequestExclusiveMode);
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
FirstDlgCmd::~FirstDlgCmd()
{
}


//  Overload this method: when your command gains focus
//
// Activates a command.
//   iFromClient :The command that requests to activate the current one.
//   iEvtDat :The notification sent.
// ----------------------------------------------------
CATStatusChangeRC FirstDlgCmd::Activate( CATCommand * iFromClient, CATNotification * iEvtDat)
{

	FirstDlg* pDlg = new FirstDlg();
	pDlg->Build();
	pDlg->SetVisibility(CATDlgShow);
  RequestDelayedDestruction();


  return (CATStatusChangeRCCompleted);
}

//  Overload this method: when your command loses focus
//
// Deactivates a command.
//   iFromClient :The command that requests to activate the current one.
//   iEvtDat :The notification sent.
// ----------------------------------------------------
CATStatusChangeRC FirstDlgCmd::Desactivate( CATCommand * iFromClient, CATNotification * iEvtDat)
{
  return (CATStatusChangeRCCompleted);
}

//  Overload this method: when your command is canceled
//
// Cancel a command.
//   iFromClient :The command that requests to activate the current one.
//   iEvtDat :The notification sent.
// ----------------------------------------------------
CATStatusChangeRC FirstDlgCmd::Cancel( CATCommand * iFromClient, CATNotification * iEvtDat)
{
  RequestDelayedDestruction();
  return (CATStatusChangeRCCompleted);
}
