// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// FirstDlg.cpp
// The dialog : FirstDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Jan 2015  Creation: Code generated by the CAA wizard  ALI
//===================================================================
#include "FirstDlg.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#include "CATBaseUnknown.h"

#include "CATFrmEditor.h"
#include "CATDocument.h"
#include "CATDocumentServices.h"
#include "CATInit.h"
#include "CATIContainerOfDocument.h"
#include "CATIGSMFactory.h"
#include "CATIGSMPoint.h"
#include "CATIGSMProceduralView.h"
#include "CATIContainer.h"
#include "CATISpecObject.h"
#include "CATIDocRoots.h"
#include "CATIProduct.h"
#include "CATILinkableObject.h"
#include "CATIModelEvents.h"
#include "CATIRedrawEvent.h"
#include "CATIInstance.h"
#include "CATModify.h"


#include "CATIPrtContainer.h"
#include "CATISketchFactory.h"
#include "CATIPrtFactory.h"
#include "CATIPrtPart.h"
#include "CATISketch.h"


#include "CATNotification.h"
#include "iostream.h"
#include "fstream.h"
#include <sstream>
#include <string>
#include "CATHSO.h"
#include "CATDlgNotify.h"



#ifdef FirstDlg_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif




//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
FirstDlg::FirstDlg() :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"FirstDlg",CATDlgWndAutoResize|CATDlgWndNoButton|CATDlgGridLayout
//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
								)
{
//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
 _FrameFM1 = NULL;
 _LabelFM1 = NULL;
 _EditorFM1 = NULL;
 _FrameFM2 = NULL;
 _LabelFM2 = NULL;
 _EditorFM2 = NULL;
 _LabelFM3 = NULL;
 _Editor016 = NULL;
 _LabelFM4 = NULL;
 _LabelFM5 = NULL;
 _FrameFM3 = NULL;
 _PushButtonFM1 = NULL;
 _LabelFM6 = NULL;
 _EditorFM4 = NULL;
 _MultiListFM1 = NULL;
 _Frame020 = NULL;
 _PushButtonFM2 = NULL;
 _PushButton021 = NULL;
//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
FirstDlg::~FirstDlg()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _FrameFM1 = NULL;
 _LabelFM1 = NULL;
 _EditorFM1 = NULL;
 _FrameFM2 = NULL;
 _LabelFM2 = NULL;
 _EditorFM2 = NULL;
 _LabelFM3 = NULL;
 _Editor016 = NULL;
 _LabelFM4 = NULL;
 _LabelFM5 = NULL;
 _FrameFM3 = NULL;
 _PushButtonFM1 = NULL;
 _LabelFM6 = NULL;
 _EditorFM4 = NULL;
 _MultiListFM1 = NULL;
 _Frame020 = NULL;
 _PushButtonFM2 = NULL;
 _PushButton021 = NULL;
//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
}



void FirstDlg::Build()
{
//  TODO: This call builds your dialog from the layout declaration file
//  -------------------------------------------------------------------
	pDlgFile = new CATDlgFile(this,"选择文件");
	//pDlgFile ->SetVisibility(CATDlgShow);
	CATUnicodeString nameExtension = CATUnicodeString("txt files");
	CATString filterExtension = CATString("*.txt");
	pDlgFile ->SetFilterStrings(&nameExtension, &filterExtension, 1);
	pDlgFile2 = new CATDlgFile(this,"导出",CATDlgFileSave);
	_AddNotify = new CATDlgNotify(this,"",CATDlgNfyOK);

//CAA2 WIZARD WIDGET CONSTRUCTION SECTION
 _FrameFM1 = new CATDlgFrame(this, "FrameFM1", CATDlgGridLayout);
_FrameFM1 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _LabelFM1 = new CATDlgLabel(_FrameFM1, "LabelFM1");
_LabelFM1 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _EditorFM1 = new CATDlgEditor(_FrameFM1, "EditorFM1");
_EditorFM1 -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _FrameFM2 = new CATDlgFrame(this, "FrameFM2", CATDlgGridLayout);
_FrameFM2 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _LabelFM2 = new CATDlgLabel(_FrameFM2, "LabelFM2");
_LabelFM2 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _EditorFM2 = new CATDlgEditor(_FrameFM2, "EditorFM2");
_EditorFM2 -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _LabelFM3 = new CATDlgLabel(_FrameFM2, "LabelFM3");
_LabelFM3 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _Editor016 = new CATDlgEditor(_FrameFM2, "Editor016");
_Editor016 -> SetGridConstraints(1, 1, 1, 1, CATGRID_4SIDES);
 _LabelFM4 = new CATDlgLabel(_FrameFM2, "LabelFM4");
_LabelFM4 -> SetGridConstraints(0, 2, 1, 1, CATGRID_4SIDES);
 _LabelFM5 = new CATDlgLabel(_FrameFM2, "LabelFM5");
_LabelFM5 -> SetGridConstraints(1, 2, 1, 1, CATGRID_4SIDES);
 _FrameFM3 = new CATDlgFrame(this, "FrameFM3", CATDlgGridLayout);
_FrameFM3 -> SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);
 _PushButtonFM1 = new CATDlgPushButton(_FrameFM3, "PushButtonFM1");
_PushButtonFM1 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _LabelFM6 = new CATDlgLabel(_FrameFM3, "LabelFM6");
_LabelFM6 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _EditorFM4 = new CATDlgEditor(_FrameFM3, "EditorFM4");
 _EditorFM4 -> SetVisibleTextWidth(20);
_EditorFM4 -> SetGridConstraints(1, 1, 1, 1, CATGRID_4SIDES);
 _MultiListFM1 = new CATDlgMultiList(this, "MultiListFM1");
 _MultiListFM1 -> SetVisibleTextWidth(10);
 CATUnicodeString MultiListFM1Titles [ 6 ];
 MultiListFM1Titles[0] = CATMsgCatalog::BuildMessage("FirstDlg", "MultiListFM1.ColumnTitle1");
 MultiListFM1Titles[1] = CATMsgCatalog::BuildMessage("FirstDlg", "MultiListFM1.ColumnTitle2");
 MultiListFM1Titles[2] = CATMsgCatalog::BuildMessage("FirstDlg", "MultiListFM1.ColumnTitle3");
 MultiListFM1Titles[3] = CATMsgCatalog::BuildMessage("FirstDlg", "MultiListFM1.ColumnTitle4");
 MultiListFM1Titles[4] = CATMsgCatalog::BuildMessage("FirstDlg", "MultiListFM1.ColumnTitle5");
 MultiListFM1Titles[5] = CATMsgCatalog::BuildMessage("FirstDlg", "MultiListFM1.ColumnTitle6");
 _MultiListFM1 -> SetColumnTitles(6, MultiListFM1Titles);
 _MultiListFM1 -> SetVisibleColumnCount( 6 );
_MultiListFM1 -> SetGridConstraints(3, 0, 1, 1, CATGRID_4SIDES);
 _Frame020 = new CATDlgFrame(this, "Frame020", CATDlgGridLayout);
_Frame020 -> SetGridConstraints(4, 0, 1, 1, CATGRID_4SIDES);
 _PushButtonFM2 = new CATDlgPushButton(_Frame020, "PushButtonFM2");
_PushButtonFM2 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _PushButton021 = new CATDlgPushButton(_Frame020, "PushButton021");
_PushButton021 -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION

//CAA2 WIZARD CALLBACK DECLARATION SECTION
     AddAnalyseNotificationCB (_PushButton021, 
                               _PushButton021->GetPushBActivateNotification(),
                               (CATCommandMethod)&FirstDlg::OnPushButton021PushBActivateNotification,
                               NULL);

     AddAnalyseNotificationCB (_PushButtonFM1, 
                               _PushButtonFM1->GetPushBActivateNotification(),
                               (CATCommandMethod)&FirstDlg::OnPushButtonFM1PushBActivateNotification,
                               NULL);
     AddAnalyseNotificationCB (this, 
                               GetWindCloseNotification(),
                               (CATCommandMethod)&FirstDlg::OnFirstDlgWindCloseNotification,
                               NULL);
     AddAnalyseNotificationCB (this, 
                               GetWindCloseNotification(),
                               (CATCommandMethod)&FirstDlg::OnFirstDlgWindCloseNotification,
                               NULL);
     AddAnalyseNotificationCB (_PushButtonFM2, 
                               _PushButtonFM2->GetPushBActivateNotification(),
                               (CATCommandMethod)&FirstDlg::OnPushButtonFM2PushBActivateNotification,
                               NULL);
     AddAnalyseNotificationCB (_PushButtonFM1, 
                               _PushButtonFM1->GetPushBActivateNotification(),
                               (CATCommandMethod)&FirstDlg::OnPushButtonFM1PushBActivateNotification,
                               NULL);


//END CAA2 WIZARD CALLBACK DECLARATION SECTION
	 AddAnalyseNotificationCB (pDlgFile,
		 pDlgFile->GetDiaOKNotification(),
		 (CATCommandMethod)&FirstDlg::ActOnOK,
		 NULL);
	 AddAnalyseNotificationCB (pDlgFile2,
		 pDlgFile2->GetDiaOKNotification(),
		 (CATCommandMethod)&FirstDlg::ActOnOK2,
		 NULL);

}




//-------------------------------------------------------------------------
// Callback on PushBActivate of _PushButtonFM1
//-------------------------------------------------------------------------



void FirstDlg::OnPushButtonFM1PushBActivateNotification(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{

  pDlgFile ->SetVisibility(CATDlgShow);

}

void FirstDlg::ActOnOK(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
	CATUnicodeString fileName;
	pDlgFile -> GetSelection(fileName);
	_EditorFM4 -> SetText(fileName);


	std::ifstream infile;
	infile.open(fileName.ConvertToChar(),ios::in);//打开文件
	while (!infile.eof())
	{
		std::string line;
		int i = 0;
		while (getline(infile,line))//逐行读取
		{
			std::ostringstream RowNu;
			RowNu << i+1;
			CATUnicodeString I ;
			std::string Mide = RowNu.str();
			I = Mide.c_str();
			_MultiListFM1 -> SetColumnItem(0,I,i,CATDlgDataModify);
			const char* split = ",";
			char* p ;
			p = strtok((char*)line.c_str(),split);//逗号分隔
			double val;
			for (int k = 0; p!= NULL;k++)
			{
				CATUnicodeString NU = p;
				NU.ConvertToNum(&val);
				if(k == 0)
				{
					std::ostringstream COR;
					COR << val + 2480;//坐标转换(x)
					std::string Mide = COR.str();
					CATUnicodeString Val = Mide.c_str();
					_MultiListFM1 -> SetColumnItem(k+2,Val,i,CATDlgDataModify);//填入表格
				}
				if(k == 1)
				{
					std::ostringstream COR;
					COR << val + 1528;
					std::string Mide = COR.str();
					CATUnicodeString Val = Mide.c_str();
					_MultiListFM1 -> SetColumnItem(k+2,Val,i,CATDlgDataModify);
				}
				if(k == 2)
				{
					std::ostringstream COR;
					COR << val - 6160;
					std::string Mide = COR.str();
					CATUnicodeString Val = Mide.c_str();
					_MultiListFM1 -> SetColumnItem(k-1,Val,i,CATDlgDataModify);
				}
				if(k == 3 || k == 4)
				{
					std::ostringstream COR;
					COR << val;
					std::string Mide = COR.str();
					CATUnicodeString Val = Mide.c_str();
					_MultiListFM1 -> SetColumnItem(k+1,Val,i,CATDlgDataModify);
				}

				p = strtok(NULL, split);
			}
		i++;
		}
	}
	infile.close();
	pDlgFile ->SetVisibility(CATDlgHide);
	pDlgFile = NULL;
}

//-------------------------------------------------------------------------
// Callback on PushBActivate of _PushButtonFM2
//-------------------------------------------------------------------------
void FirstDlg::OnPushButtonFM2PushBActivateNotification(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
	//装配文档根节点
	CATFrmEditor* pEditor = CATFrmEditor::GetCurrentEditor();
	CATDocument* pDoc = pEditor -> GetDocument();
	CATIDocRoots* piDocRootsDoc = NULL;
	HRESULT rc = E_FAIL;
	rc = pDoc -> QueryInterface(IID_CATIDocRoots,(void**)&piDocRootsDoc);
	CATIProduct_var spRoot = NULL_var;
	CATListValCATBaseUnknown_var *pRootProducts = piDocRootsDoc -> GiveDocRoots();
	spRoot = (*pRootProducts)[1];
	delete pRootProducts;pRootProducts = NULL;
	piDocRootsDoc -> Release();
	piDocRootsDoc = NULL;
	
	//新建文档
	CATDocument* pPrtDoc = NULL;
	CATDocumentServices::New("Part",pPrtDoc);

	//获取container
	CATIContainerOfDocument_var spConODocs = pPrtDoc;
	CATIContainer* pSpecContainer = NULL;
	HRESULT hr = spConODocs -> GetSpecContainer(pSpecContainer);

	//获取CATIPrtpart变量
	CATInit_var spInit(pPrtDoc);
	CATIPrtContainer* spPrtCont = NULL;
	spPrtCont = (CATIPrtContainer*)spInit -> GetRootContainer("CATIPrtContainer");
	CATIPrtPart_var spPart = spPrtCont ->GetPart();

	CATIGSMFactory_var spGSMFactory;
	spGSMFactory = spPrtCont;
	//设置点的坐标
	for(int i = 0; i < 10; i++)
	{
		CATUnicodeString Corx,Cory,Corz;
		_MultiListFM1 -> GetColumnItem(1,Corx,i);
		_MultiListFM1 -> GetColumnItem(2,Cory,i);
		_MultiListFM1 -> GetColumnItem(3,Corz,i);
	
		double CorX,CorY,CorZ;
		Corx.ConvertToNum(&CorX);
		Cory.ConvertToNum(&CorY);
		Corz.ConvertToNum(&CorZ);
		CATMathPoint _Point;

		_Point.SetCoord(CorX,CorY,CorZ);
		//画点
		CATISpecObject_var		spSpecPoint;

		CATIGSMPoint_var spPoint = spGSMFactory->CreatePoint(_Point);
		spSpecPoint = spPoint;				
		CATIGSMProceduralView_var spSndPntObj = spSpecPoint;
		spSndPntObj->InsertInProceduralView();
	}
	
	CATIDocRoots* piDocRootsOnDoc = NULL;
	pPrtDoc ->QueryInterface(IID_CATIDocRoots,(void**)&piDocRootsOnDoc);
	CATListValCATBaseUnknown_var* pProductList = piDocRootsOnDoc -> GiveDocRoots();
	CATBaseUnknown* pRootProduct = NULL;
	CATIProduct_var spPartRoot = NULL_var;
	pRootProduct = (*pProductList)[1];
	spPartRoot = pRootProduct;
	delete pProductList;
	pProductList = NULL;
	CATIProduct_var inst2Product = spRoot ->AddProduct(spPartRoot);

	CATIModelEvents_var spEvents = spRoot;
	CATModify ModifyEvent(spRoot);
	spEvents -> Dispatch(ModifyEvent);

	CATIRedrawEvent_var spRedraw = spRoot;
	spRedraw -> Redraw();

}



//-------------------------------------------------------------------------
// Callback on WindClose of _FirstDlg
//-------------------------------------------------------------------------
void FirstDlg::OnFirstDlgWindCloseNotification(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
    this->SetVisibility(CATDlgHide);
	this->RequestDelayedDestruction();

}




//-------------------------------------------------------------------------



//-------------------------------------------------------------------------
// Callback on PushBActivate of _PushButtonGL
//-------------------------------------------------------------------------



//-------------------------------------------------------------------------
// Callback on PushBActivate of _PushButton021
//-------------------------------------------------------------------------
void FirstDlg::OnPushButton021PushBActivateNotification(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
	pDlgFile2 -> SetVisibility(CATDlgShow);
	CATUnicodeString nameExtension = CATUnicodeString("csv files");
	CATString filterExtension = CATString("*.csv");
	pDlgFile2 -> SetFilterStrings(&nameExtension,&filterExtension,1);
	CATUnicodeString filename,name1,name2,name3;
	name1 = _EditorFM1 -> GetText();
	name2 = _EditorFM2 -> GetText();
	name3 = _Editor016 -> GetText();
	filename = name1 + "-载荷" + name2 + "N-" + name3 + "摄氏度";
	pDlgFile2 -> SetFileName(filename);

}

void FirstDlg::ActOnOK2(CATCommand*cmd,CATNotification*evt,CATCommandClientData data)
{
	CATUnicodeString newfileName;
	pDlgFile2 -> GetSelection(newfileName);
	newfileName = newfileName + ".csv";
	_AddNotify -> SetText("文件将被保存到:"+ newfileName);
	_AddNotify -> SetVisibility(CATDlgShow);
	const char *filepath=newfileName.ConvertToChar();
	ofstream outfile(filepath,ios::out|ios::trunc);
	outfile<< "编号"<<","<<"X坐标"<<","<<"Y坐标"<<","<<"Z坐标"<<","<<"应力"<<","<<"应变"<<endl;
	CATUnicodeString SequenceNumber,CorX,CorY,CorZ,Stress,Strain;
	int ColumnNum = _MultiListFM1 -> GetLineCount();
	for (int i = 0; i < ColumnNum; i++)
	{
		_MultiListFM1 -> GetColumnItem(0,SequenceNumber,i);
		_MultiListFM1 -> GetColumnItem(1,CorX,i);
		_MultiListFM1 -> GetColumnItem(2,CorY,i);
		_MultiListFM1 -> GetColumnItem(3,CorZ,i);
		_MultiListFM1 -> GetColumnItem(4,Stress,i);
		_MultiListFM1 -> GetColumnItem(5,Strain,i);
		outfile<<SequenceNumber<<","<<CorX<<","<<CorY<<","<<CorZ<<","<<Stress<<","<<Strain<<endl;
	}
	pDlgFile2 -> RequestDelayedDestruction();
	pDlgFile2 = NULL;
}
