// COPYRIGHT Dassault Systemes 2025
//===================================================================
//
// testAddin.cpp
// Provide implementation to interface 
//    CATIPRDWorkshopAddin
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Dec 2025  Creation: Code generated by the CAA wizard  Nack
//===================================================================
#include "testAddin.h"
#include "CATCreateWorkshop.h"

CATImplementClass(testAddin,
                  Implementation,
                  CATBaseUnknown,
                  CATnull );
 
MacDeclareHeader(testAddinHeader)
//-----------------------------------------------------------------------------
// testAddin : constructor
//-----------------------------------------------------------------------------
testAddin::testAddin():
    CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// testAddin : destructor
//-----------------------------------------------------------------------------
testAddin::~testAddin()
{
}
 
// Link the implementation to its interface
// ---------------------------------------



//TIE or TIEchain definitions
#include "TIE_CATIPRDWorkshopAddin.h"
TIE_CATIPRDWorkshopAddin(testAddin);


//Methods implementation

// Methods implementation
void testAddin::CreateCommands()
{
	new testAddinHeader("CX_PluginSample","testM","testCmd",(void *)NULL,CATFrmAvailable);
}

CATCmdContainer * testAddin::CreateToolbars()
{
	/////----------------------
	///// Cmd PluginSample
	/////----------------------
	NewAccess(CATCmdContainer,pCX_PluginSampleTools,CX_PluginSampleTools);

	// CX_PluginSample
	NewAccess(CATCmdStarter,pCX_PluginSample,CX_PluginSample);
	SetAccessCommand(pCX_PluginSample,"CX_PluginSample");
	SetAccessChild(pCX_PluginSampleTools,pCX_PluginSample);

	AddToolbarView(pCX_PluginSampleTools,1,Left);

	return pCX_PluginSampleTools;
}
