set ADL_DB2INSTANCE=DB2
set ADL_DFLT_RULES_LIB=ADLCMCNextArchiRules
set ADL_DIFF_LOCAL=N
set ADL_DIFF_PATH=N/A
set ADL_MERGER="D:\RADER18\intel_a\code\command\ADLMerger2.bat"
set ADL_NLS_LANG=AMERICAN_AMERICA.WE8ISO8859P1
set ADL_ORA_TNS_ADMIN=NA
set ADL_PATH=D:\RADER18\intel_a
set ADL_SITE_NAME=V5R18_B18
set ADL_TMP=C:\TEMP
set ADL_USER_PATH=D:\RADER18\intel_a\code\command
set ALLUSERSPROFILE=C:\ProgramData
set APPDATA=C:\Users\Nack\AppData\Roaming
set BLD_HOST_OS=win_b64
set CommonProgramFiles=C:\Program Files (x86)\Common Files
set CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
set CommonProgramW6432=C:\Program Files\Common Files
set COMPUTERNAME=DESKTOP-5R3KQHA
set ComSpec=C:\Windows\system32\cmd.exe
set CONDA_BAT=D:\ProgramData\anaconda3\condabin\conda.bat
set CONDA_EXE=D:\ProgramData\anaconda3\Scripts\conda.exe
set CONDA_SHLVL=0
set CorbaCppBuildROOT_PATH=\\lisa\iona\Orbix3.3\win_b64
set CorbaCppROOT_PATH=\\lisa\iona\Orbix3.3\win_b64
set CorbaJavaROOT_PATH=\\lisa\iona\Orbix3.3\win_b64
set CSCSkipTestOfMapFileValidity=1
set CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4
set CUDA_PATH_V12_4=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4
set DriverData=C:\Windows\System32\Drivers\DriverData
set DSarMakerROOT_PATH=D:\RADER18\CATWebDSarMaker
set FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
set FPS_BROWSER_USER_PROFILE_STRING=Default
set HOMEDRIVE=C:
set HOMEPATH=\Users\Nack
set INCLUDE=D:\RADER18\intel_a\tools\include\win_b64;D:\RADER18\intel_a\tools\include;D:\Program Files (x86)\Microsoft Visual Studio 8\VC\include;D:\Program Files (x86)\Microsoft Visual Studio 8\VC\atlmfc\include;D:\Program Files (x86)\Microsoft Visual Studio 8\VC\PlatformSDK\include
set Java1ROOT_PATH=C:\jdk1.1.8
set Java3ROOT_PATH=C:\jdk1.3.1_08
set JLMDeployROOT_PATH=D:\RADER18\intel_a\jlm\jlmdeploy65
set LIB=C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0;D:\Program Files (x86)\Microsoft Visual Studio 8\VC\lib\amd64;D:\Program Files (x86)\Microsoft Visual Studio 8\VC\atlmfc\lib\amd64;D:\Program Files (x86)\Microsoft Visual Studio 8\VC\PlatformSDK\lib\amd64
set LOCALAPPDATA=C:\Users\Nack\AppData\Local
set LOGONSERVER=\\DESKTOP-5R3KQHA
set mkcsClientMode=1
set mkcsOS_Buildtime=intel_a
set mkcsOS_NAME=Windows_NT
set mkcsOS_Runtime=intel_a
set mkcsROOT_PATH=D:\RADER18\intel_a
set mkcsSHLIB_NAME=PATH
set mkcsSHLIB_PATH=D:\RADER18\intel_a\code\bin
set MkmkADDON_LEVEL=MK_ORBIXCPP33 MK_ORBIXJAVA33 MK_MSCVER=1400
set MkmkADDON_LIB=C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkADDON_PATH=C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkASPNET20Internal=yes
set mkmkbuild=21803
set MkmkDictionary_PATH=D:\RADER18\intel_a\code\dictionary
set MkmkIC_PATH=D:\RADER18\intel_a\code\productIC
set MkmkIF60=yes
set MkmkIF60Internal=yes
set MkmkIF90Internal=yes
set MkmkINSTALL_PATH=D:\RADER18
set MkmkMsgCatalog_PATH=D:\RADER18\intel_a\resources\msgcatalog
set MkmkMSNET30DIR=C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0
set MkmkMSVCADDON_INCLUDE_80=D:\Program Files (x86)\Microsoft Visual Studio 8\VC\include;D:\Program Files (x86)\Microsoft Visual Studio 8\VC\atlmfc\include;D:\Program Files (x86)\Microsoft Visual Studio 8\VC\PlatformSDK\include
set MkmkMSVCADDON_LIB_80=D:\Program Files (x86)\Microsoft Visual Studio 8\VC\lib\amd64;D:\Program Files (x86)\Microsoft Visual Studio 8\VC\atlmfc\lib\amd64;D:\Program Files (x86)\Microsoft Visual Studio 8\VC\PlatformSDK\lib\amd64
set MkmkMSVCADDON_PATH_80=D:\Program Files (x86)\Microsoft Visual Studio 8\VC\bin\amd64
set MkmkMSVCDIR=D:\Program Files (x86)\Microsoft Visual Studio 8\VC
set MkmkMSVCDIR_80=D:\Program Files (x86)\Microsoft Visual Studio 8\VC
set MkmkMSVCSHARPDIR=C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkMSVJSHARPDIR=C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkMSVSADDON_PATH_80=D:\Program Files (x86)\Microsoft Visual Studio 8\Common7\Tools\Bin;D:\Program Files (x86)\Microsoft Visual Studio 8\Common7\IDE
set MkmkMSVSBINDIR=D:\Program Files (x86)\Microsoft Visual Studio 8\Common7\IDE
set MkmkOrbixCpp33=yes
set MkmkOrbixCpp33Internal=yes
set MkmkOrbixJava33=yes
set MkmkOrbixJava33Internal=yes
set MkmkOS_BitMode=64
set MkmkOS_Buildtime=win_b64
set MkmkOS_DOC=DOC
set MkmkOS_NAME=Windows_NT
set MkmkOS_Runtime=intel_a
set MkmkOS_Type=Windows
set MkmkOS_VAR=win_b64
set MkmkReffiles_PATH=D:\RADER18\intel_a\reffiles
set MkmkRMSSDK_PATH=D:\RADER18\intel_a\.\rms\rmssdksp2
set MkmkROOT_PATH=D:\RADER18\intel_a
set MkmkSHLIB_NAME=Path
set MkmkSHLIB_PATH=D:\RADER18\intel_a\code\bin
set mkmkvers=mkmk Version 2.18.3
set MkmkVERSIONINFO=NO
set MkmkVS60=yes
set MkmkVS60Internal=yes
set MkmkVS80Internal=yes
set MkmkXMLMANIFEST=NO
set MKMK_JAVAC_CMD_SIZE=32000
set Mkmk_Modifier=1034
set MKMK_NO_MONOCODE_DOC=yes
set MKMK_USEPRECOMPIL=yes
set MkodtOS_Runtime=win_b64
set MK_DEVNULL=NUL
set MK_SEPARATOR=\;
set MK_TEMPDIR=C:\temp
set NO_LOCAL_DEFINITION_FOR_IID=yes
set NTsetenvPath=D:\RADER18\intel_a\code\command\
set NUMBER_OF_PROCESSORS=8
set OneDrive=C:\Users\22493\OneDrive
set OS=Windows_NT
set OSMFEATROOT_PATH="\\atlas\tools\osmfeat\osmfeat\"
set PATH=D:\Program Files (x86)\Microsoft Visual Studio 8\VC\bin\amd64;C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727;D:\Program Files (x86)\Microsoft Visual Studio 8\Common7\Tools\Bin;D:\Program Files (x86)\Microsoft Visual Studio 8\Common7\IDE;D:\ProgramData\anaconda3\condabin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\libnvvp;C:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;D:\ProgramData\anaconda3;D:\ProgramData\anaconda3\Scripts;D:\ProgramData\anaconda\Library\mingw-w64\bin;D:\ProgramData\anaconda\Library\usr\bin;D:\ProgramData\anaconda\Library\bin;D:\ProgramData\anaconda\pkgs;C:\Program Files\NVIDIA Corporation\Nsight Compute 2024.1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Users\Nack\AppData\Local\Microsoft\WindowsApps;D:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Nack\AppData\Roaming\npm;D:\Program Files\MiKTeX\miktex\bin\x64\;D:\RADER18\intel_a\TCK\command;D:\RADER18\intel_a\code\command;D:\RADER18\intel_a\code\command;D:\RADER18\intel_a\code\command
set PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
set PROCESSOR_ARCHITECTURE=x86
set PROCESSOR_ARCHITEW6432=AMD64
set PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
set PROCESSOR_LEVEL=6
set PROCESSOR_REVISION=9e0d
set ProgramData=C:\ProgramData
set ProgramFiles=C:\Program Files (x86)
set ProgramFiles(x86)=C:\Program Files (x86)
set ProgramW6432=C:\Program Files
set PROMPT=$P$G
set PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
set PUBLIC=C:\Users\Public
set RADECATSettingPath=C:\Users\Nack\AppData\Roaming\DassaultSystemes\RADE
set RELEASEMANAGER_PATH=D:\RADER18\intel_a
set rtcode=0
set SESSIONNAME=Console
set SystemDrive=C:
set SystemRoot=C:\Windows
set TCKHelp=-
set TCKOS_Runtime=intel_a
set TCK_DATE=2025/09/26-14:12:11
set TCK_ID=V5R18_B18
set TCK_INSTALL_PATH=D:\RADER18
set TCK_LOCAL_INFO=C:\Program Files (x86)
set TCK_NAME=V5R18_B18
set TCK_NO_SERVER=true
set TCK_ROOT_PATH=D:\RADER18\intel_a
set TCK_TMP_FILE=C:\Users\Nack\AppData\Local\Temp\tckexec__Nack_24398.bat
set TEMP=C:\Users\Nack\AppData\Local\Temp
set TMP=C:\Users\Nack\AppData\Local\Temp
set TMPFILE=\adl_unset_13202.bat
set USERDOMAIN=DESKTOP-5R3KQHA
set USERDOMAIN_ROAMINGPROFILE=DESKTOP-5R3KQHA
set USERNAME=Nack
set USERPROFILE=C:\Users\Nack
set VBTtmp=C:\Users\Nack\AppData\Local\Temp
set VS80COMNTOOLS=D:\Program Files (x86)\Microsoft Visual Studio 8\Common7\Tools\
set WecVersionForRosebud.3A5C=2
set windir=C:\Windows
set _tck_exec=OK
set __COMPAT_LAYER=ElevateCreateProcess
