// COPYRIGHT Dassault Systemes 2025
//===================================================================
//
// AxisDlgCmd.h
// The state chart based command: AxisDlgCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  Jun 2025  Creation: Code generated by the CAA wizard  user
//===================================================================
#ifndef AxisDlgCmd_H
#define AxisDlgCmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "AxisDlg.h"
#include "CATDialogAgent.h"
#include "CATPathElementAgent.h"
#include "CATIndicationAgent.h"

class CATIndicationAgent;

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class AxisDlgCmd: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( AxisDlgCmd, CATStateCommand )

  public:

  AxisDlgCmd();
  virtual ~AxisDlgCmd();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
  virtual void     BuildGraph();

    /**
     * Action associated to state transitions.
     */
  virtual CATBoolean  ActionOne(void * data);

  virtual CATBoolean  DesignBegin(void * data);
  virtual CATBoolean  ChooseLineC1(void * data);
  virtual CATBoolean  ChooseLineC2(void * data);
  virtual CATBoolean  ChooseCP1(void * data);
  virtual CATBoolean  ChooseCP2(void * data);

  virtual CATBoolean  ChooseSC(void * data);
  private:

  CATIndicationAgent	* _Indication;
  AxisDlg* pAxisDlg;

  CATDialogAgent* pdlgAgentLine; //´°¿Ú-Ïß
  CATDialogAgent* pdlgAgentCircle; //´°¿Ú-Ô²
  CATDialogAgent* pdlgAgentSCircle; //´°¿Ú-µ¥¶ÀÔ²
  CATPathElementAgent * pSelectionPnt1; //Ô²-Ïß
  CATPathElementAgent * pSelectionPnt2; //Ô²-Ïß
  CATPathElementAgent * pSelectionCircle1; //Ô²-Ô²
  CATPathElementAgent * pSelectionCircle2; //Ô²-Ô²
};

//----------------------------------------------------------------------

#endif
