// COPYRIGHT Dassault Systemes 2025
//===================================================================
//
// AxisDlg.h
// The dialog : AxisDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  Jun 2025  Creation: Code generated by the CAA wizard  user
//===================================================================
#ifndef AxisDlg_H
#define AxisDlg_H

#include "CATDlgDialog.h"
#include "CATDlgInclude.h"
#include "CATDlgPushButton.h"
#include "CATBaseUnknown.h"
#include "CATUnicodeString.h"
#include "CATPathElement.h"
#include <vector>
//----------------------------------------------------------------------

/**
 * Describe the purpose of your panel here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog framework.
 * (consult base class description).
 */
class AxisDlg: public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( AxisDlg, CATDlgDialog )

  public:

  AxisDlg();
  virtual ~AxisDlg();

  void Build ();

  virtual CATDlgPushButton*GetFiled(int chosenbutton);
  static void CalLine(const std::vector<double> p1, const std::vector<double> p2, const char* filepath);//线插补
  static void CalCircle(const std::vector<double> p1, const std::vector<double> p2, const char* filepath); //圆插补
  static void GetCircleParameter(CATBaseUnknown *pcir, CATPathElement* pcirpath, std::vector<double>& cirparameters); //处理圆形几何
  static void GetPntParameter(CATBaseUnknown *ppnt, CATPathElement* ppntpath, std::vector<double>& pntparameters); //处理圆形几何

  CATDlgEditor*      _Editor003;

  protected:
 
  //自动生成一个管路模型（随机参数）
  virtual void OnPushButton006PushBActivateNotification (CATCommand *, CATNotification* , CATCommandClientData data);

  virtual void OnAxisDlgWindCloseNotification (CATCommand *, CATNotification* , CATCommandClientData data);

  private:


//CAA2 WIZARD WIDGET DECLARATION SECTION
 CATDlgPushButton*      _PushButton001;
 CATDlgPushButton*      _PushButton002;
 CATDlgLabel*      _Label004;
 CATDlgPushButton*      _PushButton005;
 CATDlgPushButton*      _PushButton006;
//END CAA2 WIZARD WIDGET DECLARATION SECTION
};

//----------------------------------------------------------------------

#endif
