D:\CatiaWS\NackWsp\.\testFrm\various\win_b64\HList\PrivateInterfaces.hl
D:\CatiaWS\NackWsp\.\testFrm\various\win_b64\HList\ProtectedInterfaces.hl
D:\CatiaWS\NackWsp\.\testFrm\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\AdvancedMathematics\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\AdvancedMathematics\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\ApplicationFrame\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\ApplicationFrame\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\AutomationInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\AutomationInterfaces\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\BatchInfrastructure\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\BatchInfrastructure\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CAT3DXmlInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CAT3DXmlInterfaces\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATDataCompatibilityInfra\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATDataCompatibilityInfra\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATGraphicProperties\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATGraphicProperties\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATIAApplicationFrame\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATIAApplicationFrame\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATIADataBasics\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATIADataBasics\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATIADataMacFortran\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATIADataMacFortran\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATImmWtpInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATImmWtpInterfaces\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATJavaBridge\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATJavaBridge\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATPDMBaseInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATPDMBaseInterfaces\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATPLMDictionary\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATPLMDictionary\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATSmarTeamIntegInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATSmarTeamIntegInterfaces\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATSubdivisionObjects\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATSubdivisionObjects\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATTechnologicalPackageUIItf\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATTechnologicalPackageUIItf\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATV4System\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATV4System\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATVirtualVaultSystem\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATVirtualVaultSystem\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATXDocLinkInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\CATXDocLinkInterfaces\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\Communications\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\Communications\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\ComponentsCatalogsInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\ComponentsCatalogsInterfaces\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\Dialog\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\Dialog\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\DialogEngine\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\DialogEngine\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\FileMenu\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\FileMenu\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\GenericNaming\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\GenericNaming\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\GeometricObjects\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\GeometricObjects\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\GeometricObjectsCGM\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\GeometricObjectsCGM\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\GeometricOperators\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\GeometricOperators\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\Graph\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\Graph\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\HLRBase\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\HLRBase\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\InfInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\InfInterfaces\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\InteractiveInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\InteractiveInterfaces\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\KnowledgeInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\KnowledgeInterfaces\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\KnowledgeModeler\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\KnowledgeModeler\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\LiteralFeatures\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\LiteralFeatures\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\LiteralsEditor\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\LiteralsEditor\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\Mainwin\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\Mainwin\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\Mathematics\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\Mathematics\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\MecModInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\MecModInterfaces\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\Multimedia\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\Multimedia\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\NewTopologicalObjects\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\NewTopologicalObjects\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\ObjectModelerBase\various\win_b64\HList\PrivateInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\ObjectModelerBase\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\ObjectModelerBase\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\ObjectModelerBaseUI\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\ObjectModelerBaseUI\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\ObjectModelerCATIA\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\ObjectModelerCATIA\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\ObjectModelerInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\ObjectModelerInterfaces\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\ObjectSpecsModeler\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\ObjectSpecsModeler\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\PolygonalTools\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\PolygonalTools\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\PolyhedralInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\PolyhedralInterfaces\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\PolyhedralMathematics\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\PolyhedralMathematics\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\PolyhedralObjects\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\PolyhedralObjects\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\PolyhedralOperators\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\PolyhedralOperators\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\Print\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\Print\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\PrintBase\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\PrintBase\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\ProductStructure\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\ProductStructure\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\ProductStructureInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\ProductStructureInterfaces\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\ProductStructureUI\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\ProductStructureUI\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\SketcherInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\SketcherInterfaces\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\SpecialAPI\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\SpecialAPI\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\System\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\System\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\Tessellation\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\Tessellation\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\VBA\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\VBA\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\Visualization\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\Visualization\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\VisualizationBase\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\VisualizationBase\various\win_b64\HList\PublicInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\XMLParser\various\win_b64\HList\ProtectedInterfaces.hl
D:\Program Files\Dassault Systemes\B18\.\XMLParser\various\win_b64\HList\PublicInterfaces.hl
