// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// TrainAddin.h
// Provide implementation to interface
//    CATIAfrGeneralWksAddin

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//IMPLEMENTATION
//    TIE: CATIAfrGeneralWksAddin

//End CAA2 Wizard Generation Report
//
//  Jan 2015  Creation: Code generated by the CAA wizard  ALI
//===================================================================
#ifndef TrainAddin_H
#define TrainAddin_H

#include "CATBaseUnknown.h"
#include "CATCmdContainer.h"//创建container时用到
#include "CATCommandHeader.h"//创建header时用到
#include "CATCreateWorkshop.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATIAfrGeneralWksAddin
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class TrainAddin: public CATBaseUnknown

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     TrainAddin ();
     virtual ~TrainAddin ();
	void CreateCommands();//创建命令
	CATCmdContainer *CreateToolbars();//创建工具条


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  TrainAddin (TrainAddin &);
  TrainAddin& operator=(TrainAddin&);

};

//-----------------------------------------------------------------------

#endif
