// COPYRIGHT Dassault Systemes 2026
//===================================================================
//
// AddDocCmd.cpp
// The state chart based command: AddDocCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Jan 2026  Creation: Code generated by the CAA wizard  Nack
//===================================================================
#include "AddDocCmd.h"
#include "CATIndicationAgent.h"
#include "CATMathPlane.h"

#include "CATCreateExternalObject.h"
CATCreateClass( AddDocCmd);


//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
AddDocCmd::AddDocCmd() :
  CATStateCommand ("AddDocCmd", CATDlgEngOneShot, CATCommandModeExclusive) 
//  Valid states are CATDlgEngOneShot and CATDlgEngRepeat
  ,_Indication(NULL)
  ,_pDlg(NULL)
{
	_pDlg = new AddDocDlg();
	_pDlg->Build();
	_pDlg->SetVisibility(CATDlgShow);
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
AddDocCmd::~AddDocCmd()
{
   if (_Indication != NULL) 
      _Indication->RequestDelayedDestruction();
   	if (_pDlg)
		_pDlg->RequestDelayedDestruction();
}


//-------------------------------------------------------------------------
// BuildGraph()
//-------------------------------------------------------------------------
void AddDocCmd::BuildGraph()
{


  // TODO: Define the StateChart 
  // ---------------------------
  _Indication = new CATIndicationAgent ("Indication");
  CATMathPlane PlaneXY;
  _Indication -> SetMathPlane (PlaneXY);
  CATDialogState * initialState = GetInitialState("initialState");
  initialState -> AddDialogAgent (_Indication);
  
  AddTransition( initialState, NULL, 
                 IsOutputSetCondition (_Indication),
                 Action ((ActionMethod) &AddDocCmd::ActionOne));
}


//-------------------------------------------------------------------------
// ActionOne ()
//-------------------------------------------------------------------------
CATBoolean AddDocCmd::ActionOne( void *data )
{
  // TODO: Define the action associated with the transition 
  // ------------------------------------------------------

  return TRUE;
}
