// COPYRIGHT Dassault Systemes 2025
//===================================================================
//
// testCmd.cpp
// The state chart based command: testCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Dec 2025  Creation: Code generated by the CAA wizard  Nack
//===================================================================
#include "testCmd.h"
#include "CATIndicationAgent.h"
#include "CATMathPlane.h"

#include "CATCreateExternalObject.h"
CATCreateClass( testCmd);


//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
testCmd::testCmd() :
  CATStateCommand ("testCmd", CATDlgEngOneShot, CATCommandModeExclusive) 
//  Valid states are CATDlgEngOneShot and CATDlgEngRepeat
  ,_Indication(NULL)
  ,_pDlg(NULL)
  , _pEditor(NULL)
  , _pHSO(NULL)
  , _pISO(NULL)
  , _pSelectCurvePathAgent(NULL)
  , _pCurveFieldAgent(NULL)
  , _pModelFieldAgent(NULL)
  , _pOKAgent(NULL)
  , _pAPPLYAgent(NULL)
  , _pCLOSEAgent(NULL)
  , _spSelectCurveObj(NULL_var)
  , _spSelectCurveProduct(NULL_var)
  , _spActiveProduct(NULL_var)
  , _spPointObj(NULL_var)
{
	_pDlg=new testDlg();
	_pDlg->Build();
	_pDlg->SetVisibility(CATDlgShow);

}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
testCmd::~testCmd()
{
   if (_Indication != NULL) 
      _Indication->RequestDelayedDestruction();
   if (_pDlg != NULL) 
	   _pDlg->RequestDelayedDestruction();
	   _pDlg = NULL;
}


//-------------------------------------------------------------------------
// BuildGraph()
//-------------------------------------------------------------------------
void testCmd::BuildGraph()
{


  // TODO: Define the StateChart 
  // ---------------------------
  _Indication = new CATIndicationAgent ("Indication");
  CATMathPlane PlaneXY;
  _Indication -> SetMathPlane (PlaneXY);
  CATDialogState * initialState = GetInitialState("initialState");
  initialState -> AddDialogAgent (_Indication);
  
  AddTransition( initialState, NULL, 
                 IsOutputSetCondition (_Indication),
                 Action ((ActionMethod) &testCmd::ActionOne));
}


//-------------------------------------------------------------------------
// ActionOne ()
//-------------------------------------------------------------------------
CATBoolean testCmd::ActionOne( void *data )
{
  // TODO: Define the action associated with the transition 
  // ------------------------------------------------------

  return TRUE;
}
