// COPYRIGHT Dassault Systemes 2025
//===================================================================
//
// testDlg.cpp
// The dialog : testDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Dec 2025  Creation: Code generated by the CAA wizard  Nack
//===================================================================
#include "testDlg.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#ifdef testDlg_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif




//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
testDlg::testDlg() :
CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
			  //CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"testDlg",CATDlgWndBtnOKApplyClose|CATDlgGridLayout
			  //END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
			  )
{
	//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
 _Label001 = NULL;
 _Label002 = NULL;
 _Label003 = NULL;
 _Combo004 = NULL;
 _Spinner005 = NULL;
 _SelectorList006 = NULL;
	//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
testDlg::~testDlg()
{
	//  Do not delete the control elements of your dialog: 
	//     this is done automatically
	//  --------------------------------------------------
	//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _Label001 = NULL;
 _Label002 = NULL;
 _Label003 = NULL;
 _Combo004 = NULL;
 _Spinner005 = NULL;
 _SelectorList006 = NULL;
	//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
}



void testDlg::Build()
{
	//  TODO: This call builds your dialog from the layout declaration file
	//  -------------------------------------------------------------------

	//CAA2 WIZARD WIDGET CONSTRUCTION SECTION
 _Label001 = new CATDlgLabel(this, "Label001");
_Label001 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Label002 = new CATDlgLabel(this, "Label002");
_Label002 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _Label003 = new CATDlgLabel(this, "Label003");
_Label003 -> SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);
 _Combo004 = new CATDlgCombo(this, "Combo004", CATDlgCmbDropDown);
_Combo004 -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _Spinner005 = new CATDlgSpinner(this, "Spinner005", CATDlgSpnEntry|CATDlgSpnDouble);
 _Spinner005 -> SetMinMaxStep(0.000000, 10.000000, 0.001000);
 _Spinner005 -> SetUnit (CATDlgControl::Millimeter);
 _Spinner005 -> SetPrecision( 0 );
_Spinner005 -> SetGridConstraints(2, 1, 1, 1, CATGRID_4SIDES);
 _SelectorList006 = new CATDlgSelectorList(this, "SelectorList006");
 _SelectorList006 -> SetVisibleTextHeight(1);
 _SelectorList006 -> SetVisibleTextWidth(14);
_SelectorList006 -> SetGridConstraints(1, 1, 1, 1, CATGRID_4SIDES);
	//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION

	//CAA2 WIZARD CALLBACK DECLARATION SECTION
	//END CAA2 WIZARD CALLBACK DECLARATION SECTION
	BuildMore();
}

void testDlg::BuildMore()
{
	_SelectorList006->ClearLine();
	_SelectorList006->SetLine("No selection",0,CATDlgDataModify);
	int iTabRow = 0; 
	_SelectorList006->SetSelect(&iTabRow,1,0);

	_Combo004->ClearLine();
	_Combo004->SetLine("曲线上的距离",1);
	_Combo004->SetLine("圆的中心",1);
	_Combo004->SetField("曲线上的距离");

	_Spinner005->SetValue(0.000010);
}

CATDlgSelectorList* testDlg::GetSelectorList(int iValue)
{
	switch (iValue)
	{
	case 1: return _SelectorList006; // 返回 SelectorList
	}
	return NULL;
}

CATDlgCombo* testDlg::GetCombo(int iValue)
{
	switch (iValue)
	{
	case 1: return _Combo004; // 返回 Combo
	}
	return NULL;
}

CATDlgSpinner* testDlg::GetSpinner(int iValue)
{
	switch (iValue)
	{
	case 1: return _Spinner005; // 返回 Spinner
	}
	return NULL;
}
