// COPYRIGHT Dassault Systemes 2025
//===================================================================
//
// testCmd.h
// The state chart based command: testCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  Dec 2025  Creation: Code generated by the CAA wizard  Nack
//===================================================================
#ifndef testCmd_H
#define testCmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "testDlg.h"
#include "CATDialogAgent.h"
#include "CATPathElementAgent.h"
#include "CATHSO.h"
#include "CATISO.h"
#include "CATISpecObject.h"
#include "CATIProduct.h"
#include "CATFrmEditor.h"
class CATIndicationAgent;

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class testCmd: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( testCmd, CATStateCommand )

  public:

  testCmd();
  virtual ~testCmd();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
  virtual void     BuildGraph();

    /**
     * Action associated to state transitions.
     */
  virtual CATBoolean  ActionOne(void * data);

  private:

  CATIndicationAgent	* _Indication;
  testDlg* _pDlg;

  CATFrmEditor * _pEditor;   // 当前编辑器
  CATHSO       * _pHSO;      // 高亮选择对象
  CATISO       * _pISO;      // 隔离选择对象

  CATPathElementAgent* _pSelectCurvePathAgent; //选择元素
  CATDialogAgent* _pCurveFieldAgent;  // 单击元素
  CATDialogAgent* _pModelFieldAgent;  // 选择模式
  CATDialogAgent* _pOKAgent;          // OK
  CATDialogAgent* _pAPPLYAgent;       // APPLY
  CATDialogAgent* _pCLOSEAgent;       // CLOSE

  CATISpecObject_var   _spSelectCurveObj;        // 选择的元素
  CATIProduct_var     _spSelectCurveProduct;    // 选择元素所在的 Product
  CATIProduct_var     _spActiveProduct;          // 当前激活的 Product

  CATISpecObject_var   _spPointObj;               // 创建的点

};

//----------------------------------------------------------------------

#endif
