// COPYRIGHT Dassault Systemes 2025
//===================================================================
//
// testDlg.h
// The dialog : testDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Dec 2025  Creation: Code generated by the CAA wizard  Nack
//===================================================================
#ifndef testDlg_H
#define testDlg_H

#include "CATDlgDialog.h"
#include "CATDlgInclude.h"

//----------------------------------------------------------------------

/**
 * Describe the purpose of your panel here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog framework.
 * (consult base class description).
 */
class testDlg: public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( testDlg, CATDlgDialog )

  public:

  testDlg();
  virtual ~testDlg();

  void Build ();
  void BuildMore();
  CATDlgSelectorList* GetSelectorList(int iValue);
  CATDlgCombo*        GetCombo(int iValue);
  CATDlgSpinner*      GetSpinner(int iValue);


  protected:

  private:


//CAA2 WIZARD WIDGET DECLARATION SECTION
 CATDlgLabel*      _Label001;
 CATDlgLabel*      _Label002;
 CATDlgLabel*      _Label003;
 CATDlgCombo*      _Combo004;
 CATDlgSpinner*      _Spinner005;
 CATDlgSelectorList*      _SelectorList006;
//END CAA2 WIZARD WIDGET DECLARATION SECTION


//END CAA2 WIZARD WIDGET DECLARATION SECTION
};

//----------------------------------------------------------------------

#endif
