# COPYRIGHT Dassault Systemes 2025
#======================================================================
# Imakefile for module testAddinM.m
#======================================================================
#
#  Dec 2025  Creation: Code generated by the CAA wizard  Nack
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP \
JS0FM JS0GROUP CATPrsWksPRDWorkshop ProductStructureUIUUID 
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES) CATApplicationFrame  \

# System dependant variables 
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
