// COPYRIGHT Dassault Systemes 2025
//===================================================================
//
// testAddin.h
// Provide implementation to interface
//    CATIPRDWorkshopAddin

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//IMPLEMENTATION
//    TIE: CATIPRDWorkshopAddin

//End CAA2 Wizard Generation Report
//
//  Dec 2025  Creation: Code generated by the CAA wizard  Nack
//===================================================================
#ifndef testAddin_H
#define testAddin_H

#include "CATBaseUnknown.h"
#include "CATCommandHeader.h"
#include "CATCmdContainer.h"
//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATIPRDWorkshopAddin
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class testAddin: public CATBaseUnknown

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     testAddin ();
     virtual ~testAddin ();
	 void CreateCommands();
	 CATCmdContainer * CreateToolbars();


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  testAddin (testAddin &);
  testAddin& operator=(testAddin&);

};

//-----------------------------------------------------------------------

#endif
