// COPYRIGHT Dassault Systemes 2025
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework testFrm
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Dec 2025  Creation: Code generated by the CAA wizard  Nack
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Protected);
AddPrereqComponent("DialogEngine",Protected);
AddPrereqComponent("Mathematics",Protected);
AddPrereqComponent("Dialog",Protected);
AddPrereqComponent("ApplicationFrame",Public);
AddPrereqComponent("ProductStructureUI",Protected);
AddPrereqComponent("ObjectSpecsModeler", Public);
AddPrereqComponent("ProductStructure", Public);
// END WIZARD EDITION ZONE
