# COPYRIGHT Dassault Systemes 2026
#======================================================================
# Imakefile for module CalculateAllowanceM.m
#======================================================================
#
#  Jan 2026  Creation: Code generated by the CAA wizard  Nack
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP \
JS0GROUP JS0FM DI0PANV2 CATApplicationFrame  \
CATMathematics CATDialogEngine 
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
