// COPYRIGHT Dassault Systemes 2025
//===================================================================
//
// AxisDlgCmd.cpp
// The state chart based command: AxisDlgCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Jun 2025  Creation: Code generated by the CAA wizard  user
//===================================================================
#include "AxisDlgCmd.h"
#include "CATIndicationAgent.h"
#include "CATFrmEditor.h"
#include "CATMathPlane.h"
#include "CATPoint.h"
#include "CATCircle.h"
#include "CATLine.h"
#include "CATHSO.h"
#include "CATDialogState.h"
#include <iostream>


#include "CATCreateExternalObject.h"
CATCreateClass( AxisDlgCmd);

std::vector<double> Point1;
std::vector<double> Point2;
std::vector<double> CirclePoint1;
std::vector<double> CirclePoint2;
//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
AxisDlgCmd::AxisDlgCmd() :
  CATStateCommand ("AxisDlgCmd", CATDlgEngOneShot, CATCommandModeExclusive) 
//  Valid states are CATDlgEngOneShot and CATDlgEngRepeat
  ,_Indication(NULL)
{
	pAxisDlg = new AxisDlg();
	pAxisDlg->Build();
	pAxisDlg->SetVisibility(CATDlgShow);
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
AxisDlgCmd::~AxisDlgCmd()
{
   if (_Indication != NULL) 
      _Indication->RequestDelayedDestruction();
}


//-------------------------------------------------------------------------
// BuildGraph()
//-------------------------------------------------------------------------
void AxisDlgCmd::BuildGraph()
{
  // TODO: Define the StateChart 
  // ---------------------------
  _Indication = new CATIndicationAgent ("Indication");

  pdlgAgentLine = new CATDialogAgent("dlgAgentLine");//线
  pdlgAgentLine -> AcceptOnNotify(pAxisDlg->GetFiled(1),pAxisDlg->GetFiled(1)->GetPushBActivateNotification());

  pdlgAgentCircle = new CATDialogAgent("dlgAgentCircle");//圆
  pdlgAgentCircle -> AcceptOnNotify(pAxisDlg->GetFiled(2),pAxisDlg->GetFiled(2)->GetPushBActivateNotification());

  pdlgAgentSCircle = new CATDialogAgent("dlgAgentSCircle");
  pdlgAgentSCircle -> AcceptOnNotify(pAxisDlg->GetFiled(3),pAxisDlg->GetFiled(3)->GetPushBActivateNotification());

  pSelectionPnt1 = new CATPathElementAgent("SelectionPnt1");//代理元素，点
  pSelectionPnt1->AddElementType(CATPoint::ClassName());//
  pSelectionPnt1->SetBehavior(CATDlgEngWithPSOHSO|CATDlgEngWithPrevaluation);

  pSelectionPnt2 = new CATPathElementAgent("SelectionPnt2");//代理元素，点
  pSelectionPnt2->AddElementType(CATPoint::ClassName());//
  pSelectionPnt2->SetBehavior(CATDlgEngWithPSOHSO|CATDlgEngWithPrevaluation);

  pSelectionCircle1 = new CATPathElementAgent("SelectionPnt");//代理元素，圆
  pSelectionCircle1->AddElementType(CATCircle::ClassName());
  pSelectionCircle1->SetBehavior(CATDlgEngWithPSOHSO|CATDlgEngWithPrevaluation);

  pSelectionCircle2 = new CATPathElementAgent("SelectionPnt2");//代理元素，圆
  pSelectionCircle2->AddElementType(CATCircle::ClassName());
  pSelectionCircle2->SetBehavior(CATDlgEngWithPSOHSO|CATDlgEngWithPrevaluation);

  CATDialogState* pDlgStateActiveFirstSL = GetInitialState("等待按键激活");//初始状态
  pDlgStateActiveFirstSL->AddDialogAgent(pdlgAgentLine);
  pDlgStateActiveFirstSL->AddDialogAgent(pdlgAgentCircle);
  pDlgStateActiveFirstSL->AddDialogAgent(pdlgAgentSCircle);

  //线
  CATDialogState* pDlgGetLine1 = AddDialogState("选择线");//待选择圆状态
  pDlgGetLine1 -> AddDialogAgent(pSelectionPnt1);
  CATDialogState* pDlgGetLine2 = AddDialogState("选择线2");//待选择圆状态
  pDlgGetLine2 -> AddDialogAgent(pSelectionPnt2);
  AddTransition(pDlgStateActiveFirstSL,pDlgGetLine1,IsOutputSetCondition(pdlgAgentLine),Action((ActionMethod)&AxisDlgCmd::DesignBegin));
  AddTransition(pDlgGetLine1,pDlgGetLine2,IsOutputSetCondition(pSelectionPnt1),Action((ActionMethod)&AxisDlgCmd::ChooseLineC1));
  AddTransition(pDlgGetLine2,pDlgStateActiveFirstSL,IsOutputSetCondition(pSelectionPnt2),Action((ActionMethod)&AxisDlgCmd::ChooseLineC2));

  //圆
  CATDialogState* pDlgGetC1 = AddDialogState("选择点");//待选择圆状态
  pDlgGetC1 -> AddDialogAgent(pSelectionCircle1);
  CATDialogState* pDlgGetC2 = AddDialogState("选择点2");//待选择圆状态
  pDlgGetC2 -> AddDialogAgent(pSelectionCircle2);
  AddTransition(pDlgStateActiveFirstSL,pDlgGetC1,IsOutputSetCondition(pdlgAgentCircle),Action((ActionMethod)&AxisDlgCmd::DesignBegin));
  AddTransition(pDlgGetC1,pDlgGetC2,IsOutputSetCondition(pSelectionCircle1),Action((ActionMethod)&AxisDlgCmd::ChooseCP1));
  AddTransition(pDlgGetC2,pDlgStateActiveFirstSL,IsOutputSetCondition(pSelectionCircle2),Action((ActionMethod)&AxisDlgCmd::ChooseCP2));

  //单独取圆参数
  CATDialogState* pDlgGetCS = AddDialogState("选择圆");//待选择圆状态
  pDlgGetCS -> AddDialogAgent(pSelectionCircle1);
  AddTransition(pDlgStateActiveFirstSL,pDlgGetCS,IsOutputSetCondition(pdlgAgentSCircle),Action((ActionMethod)&AxisDlgCmd::DesignBegin));
  AddTransition(pDlgGetCS,pDlgStateActiveFirstSL,IsOutputSetCondition(pSelectionCircle1),Action((ActionMethod)&AxisDlgCmd::ChooseSC));
}


//-------------------------------------------------------------------------
// ActionOne ()
//-------------------------------------------------------------------------
CATBoolean AxisDlgCmd::ActionOne( void *data )
{
  // TODO: Define the action associated with the transition 
  // ------------------------------------------------------

  return TRUE;
}

//开始配置 
CATBoolean AxisDlgCmd::DesignBegin(void * data){
	CATFrmEditor * pEditor = CATFrmEditor::GetCurrentEditor();
	CATHSO* pHSO = pEditor->GetHSO();
	pHSO->Empty();
	std::cout << "选择几何元素" << std::endl;
	pdlgAgentLine->InitializeAcquisition();
	pdlgAgentCircle->InitializeAcquisition();
	pdlgAgentSCircle->InitializeAcquisition();
	return TRUE;
}

//直线
CATBoolean AxisDlgCmd::ChooseLineC1(void * data){
	Point1.clear();
	AxisDlg::GetPntParameter(pSelectionPnt1->GetElementValue(), pSelectionPnt1->GetValue(),Point1);
	pSelectionPnt1->InitializeAcquisition();
	return TRUE;
}

//直线
CATBoolean AxisDlgCmd::ChooseLineC2(void * data){
	Point2.clear();
	AxisDlg::GetPntParameter(pSelectionPnt2->GetElementValue(), pSelectionPnt2->GetValue(),Point2);
	CATUnicodeString filename = pAxisDlg->_Editor003->GetText();
	const char *filepath=filename.ConvertToChar();
	AxisDlg::CalLine(Point1, Point2, filepath);
	pSelectionPnt2->InitializeAcquisition();
	return TRUE;
}

//圆
CATBoolean AxisDlgCmd::ChooseCP1(void * data){
	CirclePoint1.clear();
	AxisDlg::GetCircleParameter(pSelectionCircle1->GetElementValue(), pSelectionCircle1->GetValue(),CirclePoint1);
	pSelectionCircle1->InitializeAcquisition();
	return TRUE;
}

//圆
CATBoolean AxisDlgCmd::ChooseCP2(void * data){
	CirclePoint2.clear();
	AxisDlg::GetCircleParameter(pSelectionCircle2->GetElementValue(), pSelectionCircle2->GetValue(),CirclePoint2);
	CATUnicodeString filename = pAxisDlg->_Editor003->GetText();
	const char *filepath=filename.ConvertToChar();
	AxisDlg::CalCircle(CirclePoint1, CirclePoint2, filepath);
	pSelectionCircle2->InitializeAcquisition();
	return TRUE;
}

//圆
CATBoolean AxisDlgCmd::ChooseSC(void * data){
	CirclePoint1.clear();
	AxisDlg::GetCircleParameter(pSelectionCircle1->GetElementValue(), pSelectionCircle1->GetValue(),CirclePoint1);
	pSelectionCircle1->InitializeAcquisition();
	return TRUE;
}