// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework TrainFramework
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Jan 2015  Creation: Code generated by the CAA wizard  ALI
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Protected);
AddPrereqComponent("DialogEngine",Protected);
AddPrereqComponent("Mathematics",Protected);
AddPrereqComponent("Dialog",Protected);
AddPrereqComponent("ApplicationFrame",Public);
// END WIZARD EDITION ZONE
AddPrereqComponent("ApplicationFrame",Public);
AddPrereqComponent("CATAssemblyInterfaces",Public);
AddPrereqComponent("ObjectModelerBase",Public);
AddPrereqComponent("ProductStructureUI",Public);
AddPrereqComponent("DialogEngine",Public);
AddPrereqComponent("Mathematics",Public);
AddPrereqComponent("Dialog",Public);
AddPrereqComponent("MechanicalModelerUI",Public);
AddPrereqComponent("PartInterfaces",Public);
AddPrereqComponent("ObjectSpecsModeler",Public);
AddPrereqComponent("ConstraintModeler",Public);
AddPrereqComponent("ConstraintModelerInterfaces",Public);
AddPrereqComponent("ConstraintModelerUI",Public);
AddPrereqComponent("SketcherInterfaces",Public);
AddPrereqComponent("GeometricOperators",Public);
AddPrereqComponent("ProductStructureInterfaces",Public);
AddPrereqComponent("ProductStructure",Public);
AddPrereqComponent("SpaceAnalysisInterfaces",Public);
AddPrereqComponent("SimulationBase",Public);
AddPrereqComponent("SimulationInterfaces",Public);
AddPrereqComponent("GSMInterfaces",Public);
AddPrereqComponent("GSOInterfaces",Public);
AddPrereqComponent("LiteralFeatures",Public);
AddPrereqComponent("DraftingInterfaces",Public);
AddPrereqComponent("CATTTRSInterfaces",Public);
AddPrereqComponent("CATTPSInterfaces",Public);
AddPrereqComponent("ManufacturingInterfaces",Public);
AddPrereqComponent("SurfaceMachiningInterfaces",Public);
AddPrereqComponent("DMAPSInterfaces",Public);
AddPrereqComponent("GeometricObjects",Public);
AddPrereqComponent("KnowledgeInterfaces",Public);
AddPrereqComponent("LiteralsEditor",Public);
AddPrereqComponent("MechanicalModeler",Public);
AddPrereqComponent("Tessellation",Public);
AddPrereqComponent("Visualization",Public);
AddPrereqComponent("VisualizationBase",Public);
AddPrereqComponent("MecModInterfaces",Public);
AddPrereqComponent("NewTopologicalObjects",Public);
AddPrereqComponent("MechanicalCommands",Public);
AddPrereqComponent("TopologicalOperators",Public);
AddPrereqComponent("InteractiveInterfaces",Public);
AddPrereqComponent("PrismaticMachiningInterfaces",Public);
AddPrereqComponent("ToolPathEditorInterfaces",Public);
AddPrereqComponent("FreeFormOperators",Public);
AddPrereqComponent("CATIAApplicationFrame",Public);
AddPrereqComponent("ComponentsCatalogsInterfaces",Public);
AddPrereqComponent("ProcessPlatformBase",Public);
AddPrereqComponent("ProcessPlatformVisu",Public);
AddPrereqComponent("AdvancedMachiningInterfaces",Public);
AddPrereqComponent("ObjectModelerInterfaces",Public);
AddPrereqComponent("SketcherModeler",Public);
AddPrereqComponent("MeasureGeometryInterfaces",Public);
AddPrereqComponent("InfInterfaces",Public);
AddPrereqComponent("XMLParser",Public);
AddPrereqComponent("AdvancedMathematics",Public);
AddPrereqComponent("CATPlantShipModeler",Public);
AddPrereqComponent("CATSchPlatformInterfaces",Public);

